// data_v2.js — CampQuest listings database
// Version: 2.0
// Last updated: April 2026
// Towns covered: South Orange, Maplewood (West Orange, Millburn, Livingston coming soon)
// Total listings: 45
// Sources: official program websites, Village Green, helloSOMA.com,
//          Google-indexed Facebook/Instagram pages, Patch NJ, NJ Kids Online
//
// To add a new camp, copy any object below and fill in the details.
// IDs must be unique and sequential.

const camps = [

  // ═══════════════════════════════════════════════════════════════════
  // SOUTH ORANGE
  // ═══════════════════════════════════════════════════════════════════

  {
    id: 1,
    name: "South Orange Recreation Summer Day Camp",
    town: "South Orange",
    type: "General",
    description: "The flagship South Orange municipal day camp. A seven-week program at Meadowland Park offering sports, arts and crafts, games, and special events, with twice-weekly swim. Available as half-day (9am–1pm) or full-day (9am–4pm), with extended care from 8am–5pm. Groups split by grade level, Pre-K through 8th grade. Directed by Samantha Siegel. Residents-only enrollment.",
    ageMin: 4,
    ageMax: 14,
    dates: "Seven weeks, late June – mid August 2026",
    price: "Contact for rates",
    location: "Meadowland Park, South Orange, NJ",
    contact: "ssiegel@southorange.org",
    phone: "(973) 378-7715",
    website: "https://www.southorange.org/605/South-Orange-Recreation-Summer-Camp",
    tags: ["day camp", "swimming", "sports", "arts and crafts", "general", "municipal"],
    featured: true
  },
  {
    id: 2,
    name: "South Orange Recreation – Multi-Sports Camp",
    town: "South Orange",
    type: "Sports",
    description: "Week-long multi-sport day camp run through South Orange Recreation in partnership with USA Sport Group. Kids rotate through soccer, tennis, basketball, lacrosse, golf, t-ball, flag football, pickleball, and more. All ability levels, ages 5–14. New sessions added throughout summer.",
    ageMin: 5,
    ageMax: 14,
    dates: "Weekly sessions throughout summer 2026",
    price: "Contact for rates",
    location: "Various parks, South Orange, NJ",
    contact: "sovrec@southorange.org",
    phone: "(973) 378-7754",
    website: "https://usasportgroup.com/recreation/234-south-orange-recreation-south-orange-nj",
    tags: ["sports", "multi-sport", "soccer", "tennis", "basketball", "lacrosse", "outdoor"],
    featured: false
  },
  {
    id: 3,
    name: "South Orange Recreation – Tennis Camp",
    town: "South Orange",
    type: "Sports",
    description: "Youth tennis camp run in partnership with USA Sport Group. Covers stroke production, drills, singles and doubles match play, and fitness. Ages 5–14, all skill levels.",
    ageMin: 5,
    ageMax: 14,
    dates: "Weekly sessions throughout summer 2026",
    price: "Contact for rates",
    location: "South Orange Recreation courts, South Orange, NJ",
    contact: "sovrec@southorange.org",
    phone: "(973) 378-7754",
    website: "https://usasportgroup.com/recreation/234-south-orange-recreation-south-orange-nj",
    tags: ["tennis", "sports", "outdoor", "recreation"],
    featured: false
  },
  {
    id: 4,
    name: "South Orange Recreation – Soccer Camp",
    town: "South Orange",
    type: "Sports",
    description: "Soccer-focused day camp through South Orange Recreation. Covers fundamentals, drills, and scrimmages. Available for age groups from toddler through teen.",
    ageMin: 5,
    ageMax: 14,
    dates: "Weekly sessions throughout summer 2026",
    price: "Contact for rates",
    location: "Floods Hill Field / Meadowland Park, South Orange, NJ",
    contact: "sovrec@southorange.org",
    phone: "(973) 378-7754",
    website: "https://usasportgroup.com/recreation/234-south-orange-recreation-south-orange-nj",
    tags: ["soccer", "sports", "outdoor", "recreation"],
    featured: false
  },
  {
    id: 5,
    name: "South Orange Country Day School Summer Camp",
    town: "South Orange",
    type: "General",
    description: "A nine-week Montessori-inspired summer camp for Pre-K children. Follows the same school-day structure — morning meetings, center work, storytelling, gardening, and art — with weekly science and nature themes. Available only to current and incoming Fall 2026 SOCDS students.",
    ageMin: 3,
    ageMax: 6,
    dates: "Late June – mid August 2026 (9 weeks)",
    price: "Contact for rates",
    location: "South Orange Country Day School, South Orange, NJ",
    contact: "info@socds.com",
    phone: "Contact school",
    website: "https://www.socds.com/programs",
    tags: ["Montessori", "preschool", "nature", "gardening", "art", "general"],
    featured: false
  },
  {
    id: 6,
    name: "South Mountain YMCA – Creative Theater Camp",
    town: "South Orange",
    type: "Arts",
    description: "A performing arts day camp where campers write, design, rehearse, and perform full theatrical productions. Includes singing, choreography, puppetry, set and costume design. Four levels by grade (K–8). Three 3-week sessions. Directed by Gail Green. Located at First Presbyterian and Trinity Church in South Orange.",
    ageMin: 5,
    ageMax: 14,
    dates: "June 22 – August 21, 2026 (three 3-week sessions); M–F 7:30am–3:30pm",
    price: "$1,572–$1,662/session (member/community); aftercare available",
    location: "First Presbyterian and Trinity Church, 111 Irvington Ave., South Orange, NJ",
    contact: "info@metroymcas.org",
    phone: "(973) 758-9039",
    website: "https://maplewoodymcacamp.org/creative-theater-day-camp",
    tags: ["theater", "performing arts", "singing", "dance", "arts", "production"],
    featured: true
  },
  {
    id: 7,
    name: "Class Act Performing Arts Studio – Future Starz Camp",
    town: "South Orange",
    type: "Arts",
    description: "A weekly Broadway-themed camp for young children ages 3–7. Each week campers collaborate to create and perform a mini-show based on a new theme, developing singing, movement, and storytelling. Mon–Fri, 9:30am–12:30pm. Drop-off only; all campers must be potty trained.",
    ageMin: 3,
    ageMax: 7,
    dates: "Weekly sessions throughout summer 2026 (no class July 4)",
    price: "$100 non-refundable deposit; contact for full pricing",
    location: "Class Act Performing Arts Studio, 128 Irvington Ave., South Orange, NJ",
    contact: "office@classactpas.com",
    phone: "(973) 789-0191",
    website: "https://www.classactpas.com/summerprograms",
    tags: ["performing arts", "Broadway", "dance", "singing", "preschool", "theater"],
    featured: false
  },
  {
    id: 8,
    name: "Class Act Performing Arts Studio – Musical Theatre Summer Stage",
    town: "South Orange",
    type: "Arts",
    description: "A musical theater camp for ages 7–15. Students rehearse and perform productions while building skills in acting, singing, and choreography. Two tracks: Summer Stage and CAPAS SummerStock for more advanced students.",
    ageMin: 7,
    ageMax: 15,
    dates: "Summer 2026 (multiple sessions; registration open)",
    price: "Contact for rates",
    location: "Class Act Performing Arts Studio, 128 Irvington Ave., South Orange, NJ",
    contact: "office@classactpas.com",
    phone: "(973) 789-0191",
    website: "https://www.classactpas.com/summer-intensives",
    tags: ["musical theater", "acting", "singing", "dance", "arts", "teens"],
    featured: false
  },
  {
    id: 9,
    name: "Class Act Performing Arts Studio – Summer Dance Camp",
    town: "South Orange",
    type: "Arts",
    description: "A dance-focused summer camp for two age groups: 7–10 and 11–14. Students explore multiple styles in a focused, fun environment taught by CAPAS faculty.",
    ageMin: 7,
    ageMax: 14,
    dates: "Summer 2026 (sessions TBA)",
    price: "Contact for rates",
    location: "Class Act Performing Arts Studio, 128 Irvington Ave., South Orange, NJ",
    contact: "office@classactpas.com",
    phone: "(973) 789-0191",
    website: "https://www.classactpas.com/summerprograms",
    tags: ["dance", "arts", "ballet", "jazz", "performing arts"],
    featured: false
  },
  {
    id: 10,
    name: "Lydia Johnson Dance School – Dance + Art Camp",
    town: "South Orange",
    type: "Arts",
    description: "A full-day dance and art camp for ages 6 through early high school at St. Andrew's Church in South Orange. Mornings with LJD professional dancers (ballet, modern, choreography); afternoons with Mobile Makers art studio. Teen Internship positions available. Taught by NYC professionals with credits at Radio City Music Hall, The Met Opera, and West Side Story. Scholarships available through LJD's nonprofit fund.",
    ageMin: 6,
    ageMax: 16,
    dates: "July 6–10 and July 13–17, 2026 (Mon–Fri, 9am–3:30pm)",
    price: "Contact for rates; scholarships available",
    location: "St. Andrew's Church, 160 West South Orange Ave., South Orange, NJ",
    contact: "lydiajohnsondance@gmail.com",
    phone: "Contact via website",
    website: "https://www.lydiajohnsondanceschool.com",
    tags: ["dance", "ballet", "modern", "art", "choreography", "nonprofit", "professional"],
    featured: true
  },
  {
    id: 11,
    name: "Lydia Johnson Dance School – Teen Dance Camp",
    town: "South Orange",
    type: "Arts",
    description: "A full-day intensive teen dance camp July 13–17 at St. Andrew's Church. Led by Lydia Johnson with professional guest artists — including Radio City Rockettes alumni and MFA-trained company dancers — teaching Ballet, Contemporary, Jazz, and Modern. CHS Special Dance Troupe members participate. Scholarships available.",
    ageMin: 13,
    ageMax: 18,
    dates: "July 13–17, 2026 (full day)",
    price: "Contact for rates; scholarships available",
    location: "St. Andrew's Church, 160 West South Orange Ave., South Orange, NJ",
    contact: "lydiajohnsondance@gmail.com",
    phone: "Contact via website",
    website: "https://www.lydiajohnsondanceschool.com",
    tags: ["dance", "ballet", "contemporary", "jazz", "modern", "teens", "intensive"],
    featured: false
  },
  {
    id: 12,
    name: "Funky Fun Art Summer Camp",
    town: "South Orange",
    type: "Arts",
    description: "A beloved SOMA institution run by local artist Denise Hayden, offering up to 10 weeks of art camp at The Baird Community Center in South Orange. Campers explore painting, drawing, sculpting, comic art, black light art, slime, street art, and more in a fun, non-competitive studio. Runs since 2014; returned to The Baird after its 2024 renovation. Sells out fast — full-summer registration opens first, then individual weeks.",
    ageMin: 5,
    ageMax: 13,
    dates: "Summer 2026, up to 10 weekly sessions (registration opened Jan 10, 2026)",
    price: "Contact for rates",
    location: "The Baird Community Center, 204 Irvington Ave., South Orange, NJ",
    contact: "Contact via website",
    phone: "Contact for info",
    website: "https://www.funkyfunart.com",
    tags: ["art", "painting", "drawing", "sculpture", "crafts", "creative", "studio"],
    featured: false
  },
  {
    id: 13,
    name: "Cougar Soccer Club Summer Camp",
    town: "South Orange",
    type: "Sports",
    description: "A community soccer camp run by Cougar Soccer Club — the official SOMA soccer organization serving 600+ kids across Maplewood and South Orange. Morning sessions (9am–noon, Mon–Fri) across multiple weeks in South Orange, delivered by professional training partners ESA. Open to all children regardless of club membership, ages 6–11. Financial aid available. Each camper receives a t-shirt.",
    ageMin: 6,
    ageMax: 11,
    dates: "Multiple weeks throughout summer 2026 (registration opened Jan 2026)",
    price: "$230/week + $20 field fee (SOMA residents); multi-week discount to $200/week",
    location: "South Orange parks (field confirmed 2–3 weeks prior to each session)",
    contact: "CougarSoccerClub@gmail.com",
    phone: "Contact via email",
    website: "https://cougarsoccerclub.com",
    tags: ["soccer", "sports", "outdoor", "skills", "community", "non-profit"],
    featured: true
  },

  // ═══════════════════════════════════════════════════════════════════
  // SOMA-WIDE (serving both South Orange and Maplewood)
  // ═══════════════════════════════════════════════════════════════════

  {
    id: 14,
    name: "SOMA Adult School – Children's Summer Program",
    town: "South Orange",
    type: "Academic",
    description: "A beloved à-la-carte enrichment program serving grades 1–9, organized by the South Orange-Maplewood Adult School for over 90 years. Students build their own daily schedule from 100+ classes in creative arts, music, science, and sports — up to five periods per day. Taught by local district teachers assisted by teen 'Yellow Shirt' counselors. Early care from 8am; after-care until 7pm. Need-based scholarships available.",
    ageMin: 6,
    ageMax: 15,
    dates: "Session 1: June 29–July 10; Session 2: July 13–24, 2026",
    price: "Pay per class/session; contact for rates",
    location: "South Orange Middle School, South Orange, NJ",
    contact: "lherring@somadultschool.org",
    phone: "(973) 378-7620",
    website: "https://www.somadultschool.org",
    tags: ["enrichment", "arts", "science", "music", "sports", "flexible", "academic"],
    featured: true
  },
  {
    id: 15,
    name: "SOMA Adult School – Teen Summer Workshops",
    town: "Maplewood",
    type: "Arts",
    description: "Specialized creative workshops for teens 13–17 at Columbia High School. 2026 offerings: Film (two 2-week sessions, June 22–July 17), Clay Lab (July 6–9), Studio Remix Mixed Media + Painting (July 13–16), Film Photography & Darkroom (July 6–17), Creative Writing (July 13–16), Songwriting Intensive in the CHS Music Tech Lab (July 6–17), and Audition Skills for Actors (Aug 3–7). Small groups, professional educators.",
    ageMin: 13,
    ageMax: 17,
    dates: "June 22 – August 7, 2026 (various workshops; registration open)",
    price: "Contact for per-workshop rates",
    location: "Columbia High School, Maplewood, NJ",
    contact: "schoolinfo@somadultschool.org",
    phone: "(973) 378-7620",
    website: "https://www.somadultschool.org/teensummerprogram",
    tags: ["teens", "film", "photography", "clay", "art", "writing", "music", "songwriting", "acting"],
    featured: true
  },
  {
    id: 16,
    name: "Maplewood Outside School – Bluebird Forest Camp",
    town: "Maplewood",
    type: "General",
    description: "A forest preschool camp for children ages 3–5.5 in the woods of South Mountain Reservation. Each day follows a rhythm of storytelling, outdoor exploration, art invitations, and circle time. Mon–Thu, 9am–1pm. Children must be potty trained and able to separate from a caregiver.",
    ageMin: 3,
    ageMax: 6,
    dates: "Week of June 8 – August 6, 2026 (Mon–Thu, 9am–1pm)",
    price: "$335/week",
    location: "South Mountain Reservation (departing from 513 Valley St., Maplewood)",
    contact: "info@maplewoodoutsideschool.com",
    phone: "(917) 544-9485",
    website: "https://maplewoodoutsideschool.com/summer",
    tags: ["forest school", "nature", "preschool", "outdoor", "hiking", "art"],
    featured: true
  },
  {
    id: 17,
    name: "Maplewood Outside School – Sparrow Forest Camp",
    town: "Maplewood",
    type: "General",
    description: "A full-day outdoor adventure camp for ages 6–9 in South Mountain Reservation. Campers track wildlife, build forts, do science experiments, and explore waterfalls. Mon–Thu, 9am–3pm. Campers must hike up to 3 miles per day.",
    ageMin: 6,
    ageMax: 9,
    dates: "Week of June 22 – July 30, 2026 (Mon–Thu, 9am–3pm)",
    price: "$475/week",
    location: "South Mountain Reservation (departing from 513 Valley St., Maplewood)",
    contact: "info@maplewoodoutsideschool.com",
    phone: "(917) 544-9485",
    website: "https://maplewoodoutsideschool.com/summer",
    tags: ["forest school", "nature", "outdoor", "hiking", "science", "adventure"],
    featured: false
  },
  {
    id: 18,
    name: "Camp Michikamau – YMCA Sleepaway Camp",
    town: "Maplewood",
    type: "General",
    description: "A traditional overnight camp for grades 3–10, based on Lake Kanawauke in Harriman State Park, NY. Over 80 years of history. Offered through the South Mountain YMCA with bus pickup from Maplewood. Activities include rock climbing, kayaking, canoeing, archery, swimming, arts & crafts, challenge courses, and themed weekends like Color Wars. ACA-accredited.",
    ageMin: 8,
    ageMax: 16,
    dates: "Summer 2026 (two-week sessions; contact for dates)",
    price: "Contact for rates; financial assistance available",
    location: "Bus from South Mountain YMCA, 13 Jefferson Ave., Maplewood; Camp at Harriman State Park, NY",
    contact: "info@metroymcas.org",
    phone: "(973) 762-4145",
    website: "https://campmichikamau.org",
    tags: ["overnight", "sleepaway", "nature", "swimming", "archery", "rock climbing", "adventure", "YMCA"],
    featured: false
  },

  // ═══════════════════════════════════════════════════════════════════
  // MAPLEWOOD
  // ═══════════════════════════════════════════════════════════════════

  {
    id: 19,
    name: "South Mountain YMCA – SOMAPY Day Camp",
    town: "Maplewood",
    type: "General",
    description: "The YMCA's flagship general day camp for grades 1–6 at Memorial Park. Three levels (SOMAPY 1, 2, 3) by grade. Nine 2026 weekly themes: Hollywood Week, Safari, Color Wars, Medieval Times, Carnival, Under the Sea, Worldly Sports, Mad Science Mania, Game On. Mini-clinics in soccer, karate, and basketball. Swim days at Maplewood Country Club. SOMAPY 1 extends through Aug 27.",
    ageMin: 6,
    ageMax: 12,
    dates: "June 22 – August 21, 2026 (SOMAPY 1 through Aug 27); M–F 7:30am–3:30pm",
    price: "$563–$625/week (member/community); aftercare $100/week",
    location: "Memorial Park, 124 Dunnell Road, Maplewood, NJ",
    contact: "info@metroymcas.org",
    phone: "(973) 762-4145",
    website: "https://maplewoodymcacamp.org/somapy",
    tags: ["day camp", "general", "swimming", "sports", "outdoor", "YMCA"],
    featured: true
  },
  {
    id: 20,
    name: "South Mountain YMCA – Summer Discovery Camp",
    town: "Maplewood",
    type: "STEM",
    description: "A STEM-focused day camp with a new science theme each week. Hands-on experiments, group reading, outdoor play, and art projects. Two levels: SD1 (grades 1–3) and SD2 (grades 4–5). Located at St. Joseph Church. Directed by Nicole Josey.",
    ageMin: 6,
    ageMax: 11,
    dates: "June 22 – August 21, 2026; M–F 7:30am–3:30pm",
    price: "$562–$592/week (member/community); aftercare available",
    location: "St. Joseph Church, 240 Franklin Ave., Maplewood, NJ",
    contact: "info@metroymcas.org",
    phone: "(973) 758-9039",
    website: "https://maplewoodymcacamp.org/discovery",
    tags: ["STEM", "science", "outdoor", "reading", "art", "YMCA"],
    featured: false
  },
  {
    id: 21,
    name: "South Mountain YMCA – Teen Adventure Camp",
    town: "Maplewood",
    type: "General",
    description: "Action-packed camp for grades 5–9 with weekly off-site trips — Dorney Park, Camelback Beach, Laser Tag, Dave & Busters, bowling, roller skating, museums, and beaches. Includes swim, community service, and three overnights including a camp-out at Fairview Lake YMCA. Directed by Cassandra Cabrera.",
    ageMin: 10,
    ageMax: 15,
    dates: "June 22 – August 21, 2026; M–F 7:30am–3:30pm",
    price: "$595–$625/week (member/community); aftercare available",
    location: "Borden Park, 67 Orchard Rd., Maplewood, NJ",
    contact: "info@metroymcas.org",
    phone: "(973) 762-4145",
    website: "https://maplewoodymcacamp.org/teen",
    tags: ["teens", "adventure", "field trips", "swimming", "overnight", "YMCA"],
    featured: false
  },
  {
    id: 22,
    name: "South Mountain YMCA – YKnots Day Camp",
    town: "Maplewood",
    type: "General",
    description: "The YMCA's program for Pre-K through 1st grade at the South Mountain YMCA building. Builds character and social skills through storytelling, creative exploration, Natural Wonders, Amazon Artists, Dancetinations, and Drama. Staff drawn from Y preschool teachers. Directed by Taheera Hector.",
    ageMin: 3,
    ageMax: 7,
    dates: "June 22 – August 21, 2026; M–F 7:30am–3:30pm",
    price: "$562–$593/week (member/community); aftercare available",
    location: "South Mountain YMCA, 13 Jefferson Ave., Maplewood, NJ",
    contact: "info@metroymcas.org",
    phone: "(973) 762-4145",
    website: "https://maplewoodymcacamp.org/yknots",
    tags: ["preschool", "early childhood", "art", "drama", "general", "YMCA"],
    featured: false
  },
  {
    id: 23,
    name: "South Mountain YMCA – Summer Sparks Camp",
    town: "Maplewood",
    type: "STEM",
    description: "A brand-new 2026 YMCA enrichment camp for grades 1–6. Details to be finalized — an exciting addition to the Y's growing summer lineup.",
    ageMin: 6,
    ageMax: 12,
    dates: "Summer 2026 (dates TBA)",
    price: "Contact for rates",
    location: "Maplewood, NJ",
    contact: "info@metroymcas.org",
    phone: "(973) 758-9039",
    website: "https://maplewoodymcacamp.org/summer-sparks",
    tags: ["STEM", "enrichment", "YMCA", "new 2026"],
    featured: false
  },
  {
    id: 24,
    name: "South Mountain YMCA – Basketball Camp",
    town: "Maplewood",
    type: "Sports",
    description: "A specialty basketball camp for campers entering grades 2–6. Focuses on fundamentals, skill development, drills, and competitive play in a supportive environment.",
    ageMin: 7,
    ageMax: 12,
    dates: "Summer 2026 (dates TBA)",
    price: "Contact for rates",
    location: "South Mountain YMCA, 13 Jefferson Ave., Maplewood, NJ",
    contact: "info@metroymcas.org",
    phone: "(973) 762-4145",
    website: "https://maplewoodymcacamp.org/basketballcamp",
    tags: ["basketball", "sports", "YMCA", "skills"],
    featured: false
  },
  {
    id: 25,
    name: "South Mountain YMCA – Gymnastics Clinic",
    town: "Maplewood",
    type: "Sports",
    description: "A summer gymnastics clinic for campers entering grades 1–8. Directed by Lena Barnett. Covers beginner through intermediate skills.",
    ageMin: 6,
    ageMax: 14,
    dates: "Summer 2026 (dates TBA)",
    price: "Contact for rates",
    location: "South Mountain YMCA, 13 Jefferson Ave., Maplewood, NJ",
    contact: "info@metroymcas.org",
    phone: "(973) 762-4145",
    website: "https://maplewoodymcacamp.org/gymnastics",
    tags: ["gymnastics", "sports", "indoor", "YMCA"],
    featured: false
  },
  {
    id: 26,
    name: "South Mountain YMCA – Skate Camp",
    town: "Maplewood",
    type: "Sports",
    description: "A skateboarding day camp for grades 2–5. One of the only skate-specific camps in the SOMA area.",
    ageMin: 7,
    ageMax: 11,
    dates: "Summer 2026 (dates TBA)",
    price: "Contact for rates",
    location: "South Mountain YMCA / outdoor area, Maplewood, NJ",
    contact: "info@metroymcas.org",
    phone: "(973) 762-4145",
    website: "https://maplewoodymcacamp.org/skateboarding",
    tags: ["skateboarding", "sports", "outdoor", "YMCA"],
    featured: false
  },
  {
    id: 27,
    name: "South Mountain YMCA – Counselor in Training (CIT)",
    town: "Maplewood",
    type: "General",
    description: "A leadership development program for teens entering grades 9–10. CITs work alongside counselors and build mentorship and professional skills. Directed by Courtney Labossiere.",
    ageMin: 14,
    ageMax: 16,
    dates: "Summer 2026 (dates TBA)",
    price: "Contact for rates",
    location: "South Mountain YMCA, 13 Jefferson Ave., Maplewood, NJ",
    contact: "info@metroymcas.org",
    phone: "(973) 762-4145",
    website: "https://maplewoodymcacamp.org/counselor-in-training",
    tags: ["leadership", "teens", "CIT", "YMCA"],
    featured: false
  },
  {
    id: 28,
    name: "Maplewood Kids Camp",
    town: "Maplewood",
    type: "General",
    description: "Maplewood Township's official municipal day camp for kids entering Kindergarten through 5th grade. Pool trips, arts and crafts, and outdoor activities. Full-day, before-care, and after-care options available — call to register for extended care.",
    ageMin: 5,
    ageMax: 11,
    dates: "Summer 2026 (dates TBA)",
    price: "Contact for rates",
    location: "Maplewood, NJ",
    contact: "JMiranda@twp.maplewood.nj.us",
    phone: "(973) 762-8120",
    website: "https://www.maplewoodnj.gov/government/community-services/recreation/youth-programming/camp-programs",
    tags: ["day camp", "general", "swimming", "arts and crafts", "outdoor", "municipal"],
    featured: false
  },
  {
    id: 29,
    name: "Maplewood Summer Tennis Camp",
    town: "Maplewood",
    type: "Sports",
    description: "Municipal tennis camp for ages 6–14 at Memorial Park and Walter Park courts. Mon–Thu, 9am–12pm (Fri rain makeup). Covers stroke production, drills, singles and doubles tactics, and fitness.",
    ageMin: 6,
    ageMax: 14,
    dates: "Two sessions, summer 2026 (dates TBA)",
    price: "Contact for rates",
    location: "Memorial Park / Walter Park Tennis Courts, Maplewood, NJ",
    contact: "JMiranda@twp.maplewood.nj.us",
    phone: "(973) 762-8120",
    website: "https://www.maplewoodnj.gov/government/community-services/recreation/youth-programming/camp-programs",
    tags: ["tennis", "sports", "outdoor", "municipal"],
    featured: false
  },
  {
    id: 30,
    name: "Maplewood Club Tennis Camp",
    town: "Maplewood",
    type: "Sports",
    description: "One of the area's most established tennis camps, run by Director Tom Battaglia — an NCAA D1 head coach and USTA Lead Faculty Coach. Ages 5–16, all ability levels. Half-day and full-day options. Features the Maplewood Cup team competition. Sells out quickly — register early.",
    ageMin: 5,
    ageMax: 16,
    dates: "June 23 – August 21, 2026 (weekly, Mon–Thu; Fri rain makeup)",
    price: "$210–$260/week half-day (member/non-member); contact for full-day",
    location: "The Maplewood Club, Maplewood, NJ",
    contact: "Contact via website",
    phone: "Contact for info",
    website: "https://www.maplewoodclub.com/summer-camp",
    tags: ["tennis", "sports", "outdoor", "competitive", "all levels"],
    featured: false
  },
  {
    id: 31,
    name: "Maplewood Recreation – Multi-Sports Camp",
    town: "Maplewood",
    type: "Sports",
    description: "Weekly sports camps through Maplewood Recreation via USA Sport Group. Soccer, tennis, basketball, lacrosse, golf, t-ball, flag football, track & field, pickleball, field hockey, cricket, and multi-sport. Ages 2–18, all ability levels.",
    ageMin: 3,
    ageMax: 18,
    dates: "Weekly sessions throughout summer 2026",
    price: "Contact for rates",
    location: "Various parks, Maplewood, NJ",
    contact: "JMiranda@twp.maplewood.nj.us",
    phone: "(973) 762-8120",
    website: "https://usasportgroup.com/recreation/519-maplewood-recreation-maplewood-nj",
    tags: ["sports", "soccer", "tennis", "lacrosse", "basketball", "multi-sport", "outdoor"],
    featured: false
  },
  {
    id: 32,
    name: "MapleCraft Summer Art Camp",
    town: "Maplewood",
    type: "Arts",
    description: "A Maplewood Township art camp at the community art studio. Multiple rotating stations — kids choose their own projects around a weekly theme. Drawing, painting, sculpture, mixed media, and games. Supervised outdoor time each day.",
    ageMin: 5,
    ageMax: 12,
    dates: "Summer 2026 (dates TBA)",
    price: "Contact for rates",
    location: "Maplewood Community Arts Studio, Maplewood, NJ",
    contact: "JMiranda@twp.maplewood.nj.us",
    phone: "(973) 762-8120",
    website: "https://www.maplewoodnj.gov/government/community-services/recreation/youth-programming/camp-programs",
    tags: ["art", "crafts", "creative", "painting", "drawing", "municipal"],
    featured: false
  },
  {
    id: 33,
    name: "MapSo Summer Slam Basketball Camp",
    town: "Maplewood",
    type: "Sports",
    description: "A summer basketball camp for the Maplewood–South Orange community. Fundamentals, skill development, and competitive play. Part of Maplewood Community Services' summer lineup.",
    ageMin: 7,
    ageMax: 15,
    dates: "Summer 2026 (dates TBA)",
    price: "Contact for rates",
    location: "Maplewood, NJ",
    contact: "JMiranda@twp.maplewood.nj.us",
    phone: "(973) 762-8120",
    website: "https://www.maplewoodnj.gov/government/community-services/recreation/youth-programming/camp-programs",
    tags: ["basketball", "sports", "indoor", "skills"],
    featured: false
  },
  {
    id: 34,
    name: "Maplewood Mermaid Camp",
    town: "Maplewood",
    type: "Sports",
    description: "A swim-themed camp at the Maplewood Community Pool combining swim instruction, pool games, and mermaid-themed water play.",
    ageMin: 5,
    ageMax: 12,
    dates: "Summer 2026 (dates TBA)",
    price: "Contact for rates",
    location: "Maplewood Community Pool, Maplewood, NJ",
    contact: "JMiranda@twp.maplewood.nj.us",
    phone: "(973) 762-8120",
    website: "https://www.maplewoodnj.gov/government/community-services/recreation/youth-programming/camp-programs",
    tags: ["swimming", "pool", "outdoor", "water"],
    featured: false
  },
  {
    id: 35,
    name: "Maplewood Ultimate Frisbee Camp",
    town: "Maplewood",
    type: "Sports",
    description: "A specialty summer camp focused on Ultimate Frisbee. Athletic training, team strategy, and sportsmanship outdoors. Run by Maplewood Community Services.",
    ageMin: 8,
    ageMax: 15,
    dates: "Summer 2026 (dates TBA)",
    price: "Contact for rates",
    location: "Maplewood, NJ",
    contact: "JMiranda@twp.maplewood.nj.us",
    phone: "(973) 762-8120",
    website: "https://www.maplewoodnj.gov/government/community-services/recreation/youth-programming/camp-programs",
    tags: ["frisbee", "sports", "outdoor", "team"],
    featured: false
  },
  {
    id: 36,
    name: "Performers Theatre Workshop – Summer Broadway Camp",
    town: "Maplewood",
    type: "Arts",
    description: "A long-established Maplewood performing arts institution founded in 1983. Multiple summer tracks: Broadway Showcase & Training (ages 9–18), Broadway Conservatory (ages 9–18), and Young Performers (ages 4–8). Voice, acting, ballet/modern, jazz/hip-hop, tap, and musical theater. Junior campers perform locally; senior conservatory students perform at 'Don't Tell Mama' in NYC's Broadway district. Staff includes Broadway, TV, and film veterans.",
    ageMin: 4,
    ageMax: 18,
    dates: "Two 3-week sessions (contact for 2026 dates)",
    price: "Contact for rates; payment plans and early registration discounts available",
    location: "1 Pierson Road, Maplewood, NJ",
    contact: "ptwstars@gmail.com",
    phone: "(973) 327-2250",
    website: "https://ptwonline.com/classes-lessons/summer-programs/",
    tags: ["theater", "Broadway", "acting", "singing", "dance", "musical theater", "NYC showcase"],
    featured: true
  },
  {
    id: 37,
    name: "Lydia Johnson Dance School – Dance + Art Camp (Maplewood)",
    town: "Maplewood",
    type: "Arts",
    description: "The LJD Dance + Art Camp draws heavily from Maplewood families and has historically been held at the Burgdorff Performing Arts Center in Maplewood village. In 2026 the camp runs at St. Andrew's in South Orange, but this nonprofit school serves both towns equally. Taught by professional NYC company dancers. Scholarships available.",
    ageMin: 6,
    ageMax: 16,
    dates: "July 6–10 and July 13–17, 2026",
    price: "Contact for rates; scholarships available",
    location: "St. Andrew's Church, South Orange (see SO listing for full details)",
    contact: "lydiajohnsondance@gmail.com",
    phone: "Contact via website",
    website: "https://www.lydiajohnsondanceschool.com",
    tags: ["dance", "ballet", "modern", "art", "choreography", "nonprofit"],
    featured: false
  },
  {
    id: 38,
    name: "Maplewood School & Summer Program",
    town: "Maplewood",
    type: "General",
    description: "A long-running private full-day summer program featuring daily swim (Giant Water Slide!), age-appropriate sports with adapted equipment, field trips, and enrichment. Senior pool and Aqua Tot pool with American Red Cross-certified staff. Morning care, afternoon care, and bus service available. $1,000 deposit holds a spot.",
    ageMin: 3,
    ageMax: 14,
    dates: "Summer 2026 (contact for calendar; balance due April 1, 2026)",
    price: "Contact for 2026 rates",
    location: "Maplewood School, Maplewood, NJ",
    contact: "Contact via website",
    phone: "Contact for info",
    website: "https://www.maplewoodschool.com/summer-program/",
    tags: ["day camp", "swimming", "sports", "field trips", "general", "private"],
    featured: false
  },
  {
    id: 39,
    name: "Dingers NJ – Baseball & Softball Summer Camp",
    town: "Maplewood",
    type: "Sports",
    description: "Full-day baseball and softball camp at Dingers NJ, a state-of-the-art indoor training facility on Burnett Ave. Rain-or-shine: live games, HitTrax batting simulation, pool days at the Maplewood pool, whiffle ball tournaments, and Ice Cream Fridays. Rainy days: movies, bounce houses, indoor soccer, ping pong, and arcade. Aftercare available. Separate sessions for ages 6–11 and 12+.",
    ageMin: 7,
    ageMax: 13,
    dates: "Weekly sessions starting June 1, 2026 (registration open now)",
    price: "$200/week half-day clinic; contact for full-day camp rates",
    location: "Dingers NJ, 50–58 Burnett Ave, Maplewood, NJ",
    contact: "dingersnj@gmail.com",
    phone: "(973) 330-0767",
    website: "https://dingersnj.com",
    tags: ["baseball", "softball", "sports", "indoor", "batting", "HitTrax"],
    featured: false
  },
  {
    id: 40,
    name: "Kitchen Table – Kids Cooking Summer Camp",
    town: "Maplewood",
    type: "General",
    description: "A hands-on cooking camp for kids ages 8–12 at Kitchen Table, a beloved culinary studio on Springfield Ave. Led by professional chefs, campers cook and eat real food together each session. Weekly rotating themes. Camp runs July 6–August 16, 2026. Nut-free facility. Co-founded by a French Culinary Institute graduate who previously ran a children's cooking program on the Upper East Side.",
    ageMin: 8,
    ageMax: 12,
    dates: "July 6 – August 16, 2026 (weekly sessions)",
    price: "Contact for rates",
    location: "Kitchen Table, 1851 Springfield Ave (FL 2), Maplewood, NJ",
    contact: "Contact via website",
    phone: "(917) 414-4970",
    website: "https://www.kitchentablemaplewood.com",
    tags: ["cooking", "culinary", "food", "hands-on", "creative", "indoor"],
    featured: false
  },
  {
    id: 41,
    name: "SOMA Softball Camp",
    town: "Maplewood",
    type: "Sports",
    description: "A youth softball camp run by Columbia High School varsity players in Maplewood. A grassroots community program connecting high school athletes with younger players. Check website for 2026 dates and registration.",
    ageMin: 6,
    ageMax: 14,
    dates: "Summer 2026 (contact for dates)",
    price: "Contact for rates",
    location: "Maplewood, NJ",
    contact: "Contact via Facebook page",
    phone: "Contact for info",
    website: "https://orgibbons77.wixsite.com/my-site",
    tags: ["softball", "sports", "outdoor", "community", "CHS"],
    featured: false
  },

  // ─────────────────────────────────────────────────────────────────────
  // VERIFY FOR 2026 — listed on helloSOMA 2025 camp guide; confirmed
  // to exist as programs but full 2026 details not yet published online.
  // Recommend calling/emailing each before promoting heavily.
  // ─────────────────────────────────────────────────────────────────────

  {
    id: 42,
    name: "Rocket Improv Summer Camp",
    town: "South Orange",
    type: "Arts",
    description: "An improv comedy and performance camp for rising 4th–10th graders in the SOMA area. Appeared on helloSOMA's 2025 camp guide. Verify 2026 dates and details directly with the organizer.",
    ageMin: 9,
    ageMax: 16,
    dates: "Summer 2026 (verify with provider)",
    price: "Contact for rates",
    location: "South Orange / Maplewood area (verify with provider)",
    contact: "Contact via website",
    phone: "Contact for info",
    website: "https://www.hellosoma.com/summer-camps",
    tags: ["improv", "comedy", "theater", "arts", "teens"],
    featured: false
  },
  {
    id: 43,
    name: "SewLeana Fiber Arts Summer Camp",
    town: "Maplewood",
    type: "Arts",
    description: "A fiber arts and sewing camp with two tracks: Hand Sewing (ages 5–7) and Machine Sewing (ages 8+, morning and afternoon sessions). A unique, hands-on craft offering in the SOMA area. Appeared on helloSOMA's 2025 camp guide — verify 2026 details directly.",
    ageMin: 5,
    ageMax: 14,
    dates: "Summer 2026 (verify with provider)",
    price: "Contact for rates",
    location: "Maplewood / South Orange area (verify with provider)",
    contact: "Contact via website",
    phone: "Contact for info",
    website: "https://www.hellosoma.com/summer-camps",
    tags: ["sewing", "fiber arts", "crafts", "creative", "hands-on"],
    featured: false
  },
  {
    id: 44,
    name: "Motion Arts Dance Studios Summer Camp",
    town: "Maplewood",
    type: "Arts",
    description: "A summer dance camp with multiple age-group tracks (ages 6–8, 9–11, 12+, 13+). Appeared on helloSOMA's 2025 camp guide. Verify 2026 schedule, location, and pricing directly with Motion Arts.",
    ageMin: 6,
    ageMax: 17,
    dates: "Summer 2026 (verify with provider)",
    price: "Contact for rates",
    location: "Maplewood / South Orange area (verify with provider)",
    contact: "Contact via website",
    phone: "Contact for info",
    website: "https://www.hellosoma.com/summer-camps",
    tags: ["dance", "arts", "performing arts", "multiple ages"],
    featured: false
  },
  {
    id: 45,
    name: "NJ Fencing Alliance Summer Program",
    town: "Maplewood",
    type: "Sports",
    description: "The NJ Fencing Alliance, based in Maplewood, offers year-round youth fencing with Olympians on staff and is a statewide draw. Appeared on helloSOMA's camp guide — contact directly to confirm 2026 summer camp format and registration.",
    ageMin: 8,
    ageMax: 18,
    dates: "Summer 2026 (verify with provider)",
    price: "Contact for rates",
    location: "NJ Fencing Alliance, Maplewood, NJ",
    contact: "Contact via website",
    phone: "Contact for info",
    website: "https://www.hellosoma.com/summer-camps",
    tags: ["fencing", "sports", "Olympic", "indoor", "skills"],
    featured: false
  }

];
