// data.js — CampQuest listings database
// To add a new camp, copy one of the objects below and fill in the details.

const camps = [
  {
    id: 1,
    name: "South Orange Recreation Soccer Camp",
    town: "South Orange",
    type: "Sports",
    description: "A week-long day camp focused on soccer fundamentals for kids of all skill levels. Drills, scrimmages, and fun games led by experienced coaches.",
    ageMin: 6,
    ageMax: 14,
    dates: "July 7 – July 11, 2025",
    price: "$175/week",
    location: "Floods Hill Field, South Orange, NJ",
    contact: "sovrec@southorange.org",
    phone: "(973) 378-7754",
    tags: ["soccer", "sports", "outdoor", "day camp"],
    featured: true
  },
  {
    id: 2,
    name: "Maplewood Arts Studio Summer Program",
    town: "Maplewood",
    type: "Arts",
    description: "A creative summer experience covering painting, drawing, sculpture, and mixed media. Projects are displayed at an end-of-summer exhibition for families.",
    ageMin: 8,
    ageMax: 16,
    dates: "June 30 – August 8, 2025 (weekly sessions)",
    price: "$200/week",
    location: "Maplewood Community Center, Maplewood, NJ",
    contact: "arts@maplewoodarts.org",
    phone: "(973) 762-8120",
    tags: ["art", "painting", "drawing", "creative", "studio"],
    featured: true
  },
  {
    id: 3,
    name: "Livingston STEM Academy",
    town: "Livingston",
    type: "STEM",
    description: "Hands-on science and engineering camp where kids build robots, conduct experiments, and learn to code. Small group sizes ensure individual attention.",
    ageMin: 10,
    ageMax: 17,
    dates: "July 14 – July 25, 2025",
    price: "$350/week",
    location: "Livingston High School, Livingston, NJ",
    contact: "info@livingstonstem.com",
    phone: "(973) 535-8000",
    tags: ["STEM", "robotics", "coding", "science", "engineering"],
    featured: true
  },
  {
    id: 4,
    name: "West Orange Basketball Camp",
    town: "West Orange",
    type: "Sports",
    description: "Full-day basketball camp run by West Orange High School coaching staff. Focuses on fundamentals, teamwork, and competitive play. All skill levels welcome.",
    ageMin: 8,
    ageMax: 16,
    dates: "June 23 – June 27, 2025",
    price: "$150/week",
    location: "West Orange High School Gym, West Orange, NJ",
    contact: "wobasketball@westorange.org",
    phone: "(973) 669-5400",
    tags: ["basketball", "sports", "indoor", "day camp"],
    featured: false
  },
  {
    id: 5,
    name: "Millburn Summer Reading & Writing Workshop",
    town: "Millburn",
    type: "Academic",
    description: "A literacy-focused program designed to keep kids sharp over the summer. Students write short stories, read together, and work on comprehension and vocabulary.",
    ageMin: 6,
    ageMax: 12,
    dates: "July 7 – August 1, 2025 (weekly)",
    price: "$125/week",
    location: "Millburn Public Library, Millburn, NJ",
    contact: "youthprograms@millburnlibrary.org",
    phone: "(973) 376-1006",
    tags: ["reading", "writing", "academic", "literacy", "library"],
    featured: false
  },
  {
    id: 6,
    name: "South Orange Tennis Camp",
    town: "South Orange",
    type: "Sports",
    description: "Morning tennis camp at Spiotta Park courts. Beginner to intermediate instruction with a focus on technique, footwork, and match play.",
    ageMin: 7,
    ageMax: 15,
    dates: "June 30 – July 25, 2025 (Monday–Friday mornings)",
    price: "$160/week",
    location: "Spiotta Park, South Orange, NJ",
    contact: "tennis@southorange.org",
    phone: "(973) 378-7754",
    tags: ["tennis", "sports", "outdoor", "morning"],
    featured: false
  },
  {
    id: 7,
    name: "Maplewood Theater Arts Camp",
    town: "Maplewood",
    type: "Arts",
    description: "A two-week musical theater intensive culminating in a live performance for family and friends. Covers acting, singing, and stagecraft.",
    ageMin: 9,
    ageMax: 16,
    dates: "July 21 – August 1, 2025",
    price: "$425 total",
    location: "Columbia High School Auditorium, Maplewood, NJ",
    contact: "theater@maplewoodarts.org",
    phone: "(973) 762-8120",
    tags: ["theater", "acting", "singing", "performing arts", "musical"],
    featured: false
  },
  {
    id: 8,
    name: "West Orange Nature Explorers",
    town: "West Orange",
    type: "General",
    description: "An outdoor adventure program based in South Mountain Reservation. Kids hike, explore wildlife, learn about local ecology, and build nature journaling skills.",
    ageMin: 5,
    ageMax: 11,
    dates: "Weekly sessions, July 7 – August 15, 2025",
    price: "$140/week",
    location: "South Mountain Reservation, West Orange, NJ",
    contact: "nature@westorange.org",
    phone: "(973) 669-5400",
    tags: ["nature", "hiking", "outdoor", "ecology", "adventure"],
    featured: false
  },
  {
    id: 9,
    name: "Millburn Junior Chefs Cooking Camp",
    town: "Millburn",
    type: "General",
    description: "Kids learn basic cooking techniques, kitchen safety, and recipe development in a fun, hands-on setting. Each day ends with tasting what they made.",
    ageMin: 7,
    ageMax: 13,
    dates: "July 14 – July 18, 2025",
    price: "$275/week",
    location: "Millburn Community Center, Millburn, NJ",
    contact: "programs@millburnnj.org",
    phone: "(973) 564-7000",
    tags: ["cooking", "food", "hands-on", "culinary", "indoor"],
    featured: false
  },
  {
    id: 10,
    name: "Livingston Lacrosse Camp",
    town: "Livingston",
    type: "Sports",
    description: "Intensive lacrosse training for boys and girls. Coached by Livingston High School varsity staff and alumni. Separate sessions for beginners and advanced players.",
    ageMin: 8,
    ageMax: 17,
    dates: "June 23 – June 27, 2025",
    price: "$200/week",
    location: "Livingston Athletic Complex, Livingston, NJ",
    contact: "lacrosse@livingstonnj.org",
    phone: "(973) 535-8000",
    tags: ["lacrosse", "sports", "outdoor", "boys", "girls"],
    featured: false
  },
  {
    id: 11,
    name: "Maplewood Photography Workshop",
    town: "Maplewood",
    type: "Arts",
    description: "Teens learn composition, lighting, and editing using both digital cameras and smartphones. Final photos are printed and displayed at a closing gallery.",
    ageMin: 12,
    ageMax: 17,
    dates: "August 4 – August 8, 2025",
    price: "$180/week",
    location: "Maplewood Community Center, Maplewood, NJ",
    contact: "arts@maplewoodarts.org",
    phone: "(973) 762-8120",
    tags: ["photography", "art", "teens", "digital", "editing"],
    featured: false
  },
  {
    id: 12,
    name: "South Orange General Day Camp",
    town: "South Orange",
    type: "General",
    description: "A classic all-around summer day camp with swimming, sports, crafts, and field trips. Perfect for kids looking for variety and a full-day option.",
    ageMin: 4,
    ageMax: 12,
    dates: "June 30 – August 22, 2025",
    price: "$300/week",
    location: "Spiotta Park & Pool, South Orange, NJ",
    contact: "daycamp@southorange.org",
    phone: "(973) 378-7754",
    tags: ["day camp", "swimming", "sports", "crafts", "general"],
    featured: false
  }
];
