// data_v2.js — CampQuest listings database
// Version: 2.0
// Last updated: April 2026
// Towns covered: South Orange, Maplewood (West Orange, Millburn, Livingston coming soon)
// Total listings: 45
// Sources: official program websites, Village Green, helloSOMA.com,
//          Google-indexed Facebook/Instagram pages, Patch NJ, NJ Kids Online
//
// To add a new camp, copy any object below and fill in the details.
// IDs must be unique and sequential.

const camps = [

  // ═══════════════════════════════════════════════════════════════════
  // SOUTH ORANGE
  // ═══════════════════════════════════════════════════════════════════

  {
    id: 1,
    name: "South Orange Recreation Summer Day Camp",
    town: "South Orange",
    type: "General",
    description: "The flagship South Orange municipal day camp. A seven-week program at Meadowland Park offering sports, arts and crafts, games, and special events, with twice-weekly swim. Available as half-day (9am–1pm) or full-day (9am–4pm), with extended care from 8am–5pm. Groups split by grade level, Pre-K through 8th grade. Directed by Samantha Siegel. Residents-only enrollment.",
    ageMin: 4,
    ageMax: 14,
    dates: "Seven weeks, late June – mid August 2026",
    price: "Contact for rates",
    location: "Meadowland Park, South Orange, NJ",
    contact: "ssiegel@southorange.org",
    phone: "(973) 378-7715",
    website: "https://www.southorange.org/605/South-Orange-Recreation-Summer-Camp",
    tags: ["day camp", "swimming", "sports", "arts and crafts", "general", "municipal"],
    featured: true
  },
  {
    id: 2,
    name: "South Orange Recreation – Multi-Sports Camp",
    town: "South Orange",
    type: "Sports",
    description: "Week-long multi-sport day camp run through South Orange Recreation in partnership with USA Sport Group. Kids rotate through soccer, tennis, basketball, lacrosse, golf, t-ball, flag football, pickleball, and more. All ability levels, ages 5–14. New sessions added throughout summer.",
    ageMin: 5,
    ageMax: 14,
    dates: "Weekly sessions throughout summer 2026",
    price: "Contact for rates",
    location: "Various parks, South Orange, NJ",
    contact: "sovrec@southorange.org",
    phone: "(973) 378-7754",
    website: "https://usasportgroup.com/recreation/234-south-orange-recreation-south-orange-nj",
    tags: ["sports", "multi-sport", "soccer", "tennis", "basketball", "lacrosse", "outdoor"],
    featured: false
  },
  {
    id: 3,
    name: "South Orange Recreation – Tennis Camp",
    town: "South Orange",
    type: "Sports",
    description: "Youth tennis camp run in partnership with USA Sport Group. Covers stroke production, drills, singles and doubles match play, and fitness. Ages 5–14, all skill levels.",
    ageMin: 5,
    ageMax: 14,
    dates: "Weekly sessions throughout summer 2026",
    price: "Contact for rates",
    location: "South Orange Recreation courts, South Orange, NJ",
    contact: "sovrec@southorange.org",
    phone: "(973) 378-7754",
    website: "https://usasportgroup.com/recreation/234-south-orange-recreation-south-orange-nj",
    tags: ["tennis", "sports", "outdoor", "recreation"],
    featured: false
  },
  {
    id: 4,
    name: "South Orange Recreation – Soccer Camp",
    town: "South Orange",
    type: "Sports",
    description: "Soccer-focused day camp through South Orange Recreation. Covers fundamentals, drills, and scrimmages. Available for age groups from toddler through teen.",
    ageMin: 5,
    ageMax: 14,
    dates: "Weekly sessions throughout summer 2026",
    price: "Contact for rates",
    location: "Floods Hill Field / Meadowland Park, South Orange, NJ",
    contact: "sovrec@southorange.org",
    phone: "(973) 378-7754",
    website: "https://usasportgroup.com/recreation/234-south-orange-recreation-south-orange-nj",
    tags: ["soccer", "sports", "outdoor", "recreation"],
    featured: false
  },
  {
    id: 5,
    name: "South Orange Country Day School Summer Camp",
    town: "South Orange",
    type: "General",
    description: "A nine-week Montessori-inspired summer camp for Pre-K children. Follows the same school-day structure — morning meetings, center work, storytelling, gardening, and art — with weekly science and nature themes. Available only to current and incoming Fall 2026 SOCDS students.",
    ageMin: 3,
    ageMax: 6,
    dates: "Late June – mid August 2026 (9 weeks)",
    price: "Contact for rates",
    location: "South Orange Country Day School, South Orange, NJ",
    contact: "info@socds.com",
    phone: "Contact school",
    website: "https://www.socds.com/programs",
    tags: ["Montessori", "preschool", "nature", "gardening", "art", "general"],
    featured: false
  },
  {
    id: 6,
    name: "South Mountain YMCA – Creative Theater Camp",
    town: "South Orange",
    type: "Arts",
    description: "A performing arts day camp where campers write, design, rehearse, and perform full theatrical productions. Includes singing, choreography, puppetry, set and costume design. Four levels by grade (K–8). Three 3-week sessions. Directed by Gail Green. Located at First Presbyterian and Trinity Church in South Orange.",
    ageMin: 5,
    ageMax: 14,
    dates: "June 22 – August 21, 2026 (three 3-week sessions); M–F 7:30am–3:30pm",
    price: "$1,572–$1,662/session (member/community); aftercare available",
    location: "First Presbyterian and Trinity Church, 111 Irvington Ave., South Orange, NJ",
    contact: "info@metroymcas.org",
    phone: "(973) 758-9039",
    website: "https://maplewoodymcacamp.org/creative-theater-day-camp",
    tags: ["theater", "performing arts", "singing", "dance", "arts", "production"],
    featured: true
  },
  {
    id: 7,
    name: "Class Act Performing Arts Studio – Future Starz Camp",
    town: "South Orange",
    type: "Arts",
    description: "A weekly Broadway-themed camp for young children ages 3–7. Each week campers collaborate to create and perform a mini-show based on a new theme, developing singing, movement, and storytelling. Mon–Fri, 9:30am–12:30pm. Drop-off only; all campers must be potty trained.",
    ageMin: 3,
    ageMax: 7,
    dates: "Weekly sessions throughout summer 2026 (no class July 4)",
    price: "$100 non-refundable deposit; contact for full pricing",
    location: "Class Act Performing Arts Studio, 128 Irvington Ave., South Orange, NJ",
    contact: "office@classactpas.com",
    phone: "(973) 789-0191",
    website: "https://www.classactpas.com/summerprograms",
    tags: ["performing arts", "Broadway", "dance", "singing", "preschool", "theater"],
    featured: false
  },
  {
    id: 8,
    name: "Class Act Performing Arts Studio – Musical Theatre Summer Stage",
    town: "South Orange",
    type: "Arts",
    description: "A musical theater camp for ages 7–15. Students rehearse and perform productions while building skills in acting, singing, and choreography. Two tracks: Summer Stage and CAPAS SummerStock for more advanced students.",
    ageMin: 7,
    ageMax: 15,
    dates: "Summer 2026 (multiple sessions; registration open)",
    price: "Contact for rates",
    location: "Class Act Performing Arts Studio, 128 Irvington Ave., South Orange, NJ",
    contact: "office@classactpas.com",
    phone: "(973) 789-0191",
    website: "https://www.classactpas.com/summer-intensives",
    tags: ["musical theater", "acting", "singing", "dance", "arts", "teens"],
    featured: false
  },
  {
    id: 9,
    name: "Class Act Performing Arts Studio – Summer Dance Camp",
    town: "South Orange",
    type: "Arts",
    description: "A dance-focused summer camp for two age groups: 7–10 and 11–14. Students explore multiple styles in a focused, fun environment taught by CAPAS faculty.",
    ageMin: 7,
    ageMax: 14,
    dates: "Summer 2026 (sessions TBA)",
    price: "Contact for rates",
    location: "Class Act Performing Arts Studio, 128 Irvington Ave., South Orange, NJ",
    contact: "office@classactpas.com",
    phone: "(973) 789-0191",
    website: "https://www.classactpas.com/summerprograms",
    tags: ["dance", "arts", "ballet", "jazz", "performing arts"],
    featured: false
  },
  {
    id: 10,
    name: "Lydia Johnson Dance School – Dance + Art Camp",
    town: "South Orange",
    type: "Arts",
    description: "A full-day dance and art camp for ages 6 through early high school at St. Andrew's Church in South Orange. Mornings with LJD professional dancers (ballet, modern, choreography); afternoons with Mobile Makers art studio. Teen Internship positions available. Taught by NYC professionals with credits at Radio City Music Hall, The Met Opera, and West Side Story. Scholarships available through LJD's nonprofit fund.",
    ageMin: 6,
    ageMax: 16,
    dates: "July 6–10 and July 13–17, 2026 (Mon–Fri, 9am–3:30pm)",
    price: "Contact for rates; scholarships available",
    location: "St. Andrew's Church, 160 West South Orange Ave., South Orange, NJ",
    contact: "lydiajohnsondance@gmail.com",
    phone: "Contact via website",
    website: "https://www.lydiajohnsondanceschool.com",
    tags: ["dance", "ballet", "modern", "art", "choreography", "nonprofit", "professional"],
    featured: true
  },
  {
    id: 11,
    name: "Lydia Johnson Dance School – Teen Dance Camp",
    town: "South Orange",
    type: "Arts",
    description: "A full-day intensive teen dance camp July 13–17 at St. Andrew's Church. Led by Lydia Johnson with professional guest artists — including Radio City Rockettes alumni and MFA-trained company dancers — teaching Ballet, Contemporary, Jazz, and Modern. CHS Special Dance Troupe members participate. Scholarships available.",
    ageMin: 13,
    ageMax: 18,
    dates: "July 13–17, 2026 (full day)",
    price: "Contact for rates; scholarships available",
    location: "St. Andrew's Church, 160 West South Orange Ave., South Orange, NJ",
    contact: "lydiajohnsondance@gmail.com",
    phone: "Contact via website",
    website: "https://www.lydiajohnsondanceschool.com",
    tags: ["dance", "ballet", "contemporary", "jazz", "modern", "teens", "intensive"],
    featured: false
  },
  {
    id: 12,
    name: "Funky Fun Art Summer Camp",
    town: "South Orange",
    type: "Arts",
    description: "A beloved SOMA institution run by local artist Denise Hayden, offering up to 10 weeks of art camp at The Baird Community Center in South Orange. Campers explore painting, drawing, sculpting, comic art, black light art, slime, street art, and more in a fun, non-competitive studio. Runs since 2014; returned to The Baird after its 2024 renovation. Sells out fast — full-summer registration opens first, then individual weeks.",
    ageMin: 5,
    ageMax: 13,
    dates: "Summer 2026, up to 10 weekly sessions (registration opened Jan 10, 2026)",
    price: "Contact for rates",
    location: "The Baird Community Center, 204 Irvington Ave., South Orange, NJ",
    contact: "Contact via website",
    phone: "Contact for info",
    website: "https://www.funkyfunart.com",
    tags: ["art", "painting", "drawing", "sculpture", "crafts", "creative", "studio"],
    featured: false
  },
  {
    id: 13,
    name: "Cougar Soccer Club Summer Camp",
    town: "South Orange",
    type: "Sports",
    description: "A community soccer camp run by Cougar Soccer Club — the official SOMA soccer organization serving 600+ kids across Maplewood and South Orange. Morning sessions (9am–noon, Mon–Fri) across multiple weeks in South Orange, delivered by professional training partners ESA. Open to all children regardless of club membership, ages 6–11. Financial aid available. Each camper receives a t-shirt.",
    ageMin: 6,
    ageMax: 11,
    dates: "Multiple weeks throughout summer 2026 (registration opened Jan 2026)",
    price: "$230/week + $20 field fee (SOMA residents); multi-week discount to $200/week",
    location: "South Orange parks (field confirmed 2–3 weeks prior to each session)",
    contact: "CougarSoccerClub@gmail.com",
    phone: "Contact via email",
    website: "https://cougarsoccerclub.com",
    tags: ["soccer", "sports", "outdoor", "skills", "community", "non-profit"],
    featured: true
  },

  // ═══════════════════════════════════════════════════════════════════
  // SOMA-WIDE (serving both South Orange and Maplewood)
  // ═══════════════════════════════════════════════════════════════════

  {
    id: 14,
    name: "SOMA Adult School – Children's Summer Program",
    town: "South Orange",
    type: "Academic",
    description: "A beloved à-la-carte enrichment program serving grades 1–9, organized by the South Orange-Maplewood Adult School for over 90 years. Students build their own daily schedule from 100+ classes in creative arts, music, science, and sports — up to five periods per day. Taught by local district teachers assisted by teen 'Yellow Shirt' counselors. Early care from 8am; after-care until 7pm. Need-based scholarships available.",
    ageMin: 6,
    ageMax: 15,
    dates: "Session 1: June 29–July 10; Session 2: July 13–24, 2026",
    price: "Pay per class/session; contact for rates",
    location: "South Orange Middle School, South Orange, NJ",
    contact: "lherring@somadultschool.org",
    phone: "(973) 378-7620",
    website: "https://www.somadultschool.org",
    tags: ["enrichment", "arts", "science", "music", "sports", "flexible", "academic"],
    featured: true
  },
  {
    id: 15,
    name: "SOMA Adult School – Teen Summer Workshops",
    town: "Maplewood",
    type: "Arts",
    description: "Specialized creative workshops for teens 13–17 at Columbia High School. 2026 offerings: Film (two 2-week sessions, June 22–July 17), Clay Lab (July 6–9), Studio Remix Mixed Media + Painting (July 13–16), Film Photography & Darkroom (July 6–17), Creative Writing (July 13–16), Songwriting Intensive in the CHS Music Tech Lab (July 6–17), and Audition Skills for Actors (Aug 3–7). Small groups, professional educators.",
    ageMin: 13,
    ageMax: 17,
    dates: "June 22 – August 7, 2026 (various workshops; registration open)",
    price: "Contact for per-workshop rates",
    location: "Columbia High School, Maplewood, NJ",
    contact: "schoolinfo@somadultschool.org",
    phone: "(973) 378-7620",
    website: "https://www.somadultschool.org/teensummerprogram",
    tags: ["teens", "film", "photography", "clay", "art", "writing", "music", "songwriting", "acting"],
    featured: true
  },
  {
    id: 16,
    name: "Maplewood Outside School – Bluebird Forest Camp",
    town: "Maplewood",
    type: "General",
    description: "A forest preschool camp for children ages 3–5.5 in the woods of South Mountain Reservation. Each day follows a rhythm of storytelling, outdoor exploration, art invitations, and circle time. Mon–Thu, 9am–1pm. Children must be potty trained and able to separate from a caregiver.",
    ageMin: 3,
    ageMax: 6,
    dates: "Week of June 8 – August 6, 2026 (Mon–Thu, 9am–1pm)",
    price: "$335/week",
    location: "South Mountain Reservation (departing from 513 Valley St., Maplewood)",
    contact: "info@maplewoodoutsideschool.com",
    phone: "(917) 544-9485",
    website: "https://maplewoodoutsideschool.com/summer",
    tags: ["forest school", "nature", "preschool", "outdoor", "hiking", "art"],
    featured: true
  },
  {
    id: 17,
    name: "Maplewood Outside School – Sparrow Forest Camp",
    town: "Maplewood",
    type: "General",
    description: "A full-day outdoor adventure camp for ages 6–9 in South Mountain Reservation. Campers track wildlife, build forts, do science experiments, and explore waterfalls. Mon–Thu, 9am–3pm. Campers must hike up to 3 miles per day.",
    ageMin: 6,
    ageMax: 9,
    dates: "Week of June 22 – July 30, 2026 (Mon–Thu, 9am–3pm)",
    price: "$475/week",
    location: "South Mountain Reservation (departing from 513 Valley St., Maplewood)",
    contact: "info@maplewoodoutsideschool.com",
    phone: "(917) 544-9485",
    website: "https://maplewoodoutsideschool.com/summer",
    tags: ["forest school", "nature", "outdoor", "hiking", "science", "adventure"],
    featured: false
  },
  {
    id: 18,
    name: "Camp Michikamau – YMCA Sleepaway Camp",
    town: "Maplewood",
    type: "General",
    description: "A traditional overnight camp for grades 3–10, based on Lake Kanawauke in Harriman State Park, NY. Over 80 years of history. Offered through the South Mountain YMCA with bus pickup from Maplewood. Activities include rock climbing, kayaking, canoeing, archery, swimming, arts & crafts, challenge courses, and themed weekends like Color Wars. ACA-accredited.",
    ageMin: 8,
    ageMax: 16,
    dates: "Summer 2026 (two-week sessions; contact for dates)",
    price: "Contact for rates; financial assistance available",
    location: "Bus from South Mountain YMCA, 13 Jefferson Ave., Maplewood; Camp at Harriman State Park, NY",
    contact: "info@metroymcas.org",
    phone: "(973) 762-4145",
    website: "https://campmichikamau.org",
    tags: ["overnight", "sleepaway", "nature", "swimming", "archery", "rock climbing", "adventure", "YMCA"],
    featured: false
  },

  // ═══════════════════════════════════════════════════════════════════
  // MAPLEWOOD
  // ═══════════════════════════════════════════════════════════════════

  {
    id: 19,
    name: "South Mountain YMCA – SOMAPY Day Camp",
    town: "Maplewood",
    type: "General",
    description: "The YMCA's flagship general day camp for grades 1–6 at Memorial Park. Three levels (SOMAPY 1, 2, 3) by grade. Nine 2026 weekly themes: Hollywood Week, Safari, Color Wars, Medieval Times, Carnival, Under the Sea, Worldly Sports, Mad Science Mania, Game On. Mini-clinics in soccer, karate, and basketball. Swim days at Maplewood Country Club. SOMAPY 1 extends through Aug 27.",
    ageMin: 6,
    ageMax: 12,
    dates: "June 22 – August 21, 2026 (SOMAPY 1 through Aug 27); M–F 7:30am–3:30pm",
    price: "$563–$625/week (member/community); aftercare $100/week",
    location: "Memorial Park, 124 Dunnell Road, Maplewood, NJ",
    contact: "info@metroymcas.org",
    phone: "(973) 762-4145",
    website: "https://maplewoodymcacamp.org/somapy",
    tags: ["day camp", "general", "swimming", "sports", "outdoor", "YMCA"],
    featured: true
  },
  {
    id: 20,
    name: "South Mountain YMCA – Summer Discovery Camp",
    town: "Maplewood",
    type: "STEM",
    description: "A STEM-focused day camp with a new science theme each week. Hands-on experiments, group reading, outdoor play, and art projects. Two levels: SD1 (grades 1–3) and SD2 (grades 4–5). Located at St. Joseph Church. Directed by Nicole Josey.",
    ageMin: 6,
    ageMax: 11,
    dates: "June 22 – August 21, 2026; M–F 7:30am–3:30pm",
    price: "$562–$592/week (member/community); aftercare available",
    location: "St. Joseph Church, 240 Franklin Ave., Maplewood, NJ",
    contact: "info@metroymcas.org",
    phone: "(973) 758-9039",
    website: "https://maplewoodymcacamp.org/discovery",
    tags: ["STEM", "science", "outdoor", "reading", "art", "YMCA"],
    featured: false
  },
  {
    id: 21,
    name: "South Mountain YMCA – Teen Adventure Camp",
    town: "Maplewood",
    type: "General",
    description: "Action-packed camp for grades 5–9 with weekly off-site trips — Dorney Park, Camelback Beach, Laser Tag, Dave & Busters, bowling, roller skating, museums, and beaches. Includes swim, community service, and three overnights including a camp-out at Fairview Lake YMCA. Directed by Cassandra Cabrera.",
    ageMin: 10,
    ageMax: 15,
    dates: "June 22 – August 21, 2026; M–F 7:30am–3:30pm",
    price: "$595–$625/week (member/community); aftercare available",
    location: "Borden Park, 67 Orchard Rd., Maplewood, NJ",
    contact: "info@metroymcas.org",
    phone: "(973) 762-4145",
    website: "https://maplewoodymcacamp.org/teen",
    tags: ["teens", "adventure", "field trips", "swimming", "overnight", "YMCA"],
    featured: false
  },
  {
    id: 22,
    name: "South Mountain YMCA – YKnots Day Camp",
    town: "Maplewood",
    type: "General",
    description: "The YMCA's program for Pre-K through 1st grade at the South Mountain YMCA building. Builds character and social skills through storytelling, creative exploration, Natural Wonders, Amazon Artists, Dancetinations, and Drama. Staff drawn from Y preschool teachers. Directed by Taheera Hector.",
    ageMin: 3,
    ageMax: 7,
    dates: "June 22 – August 21, 2026; M–F 7:30am–3:30pm",
    price: "$562–$593/week (member/community); aftercare available",
    location: "South Mountain YMCA, 13 Jefferson Ave., Maplewood, NJ",
    contact: "info@metroymcas.org",
    phone: "(973) 762-4145",
    website: "https://maplewoodymcacamp.org/yknots",
    tags: ["preschool", "early childhood", "art", "drama", "general", "YMCA"],
    featured: false
  },
  {
    id: 23,
    name: "South Mountain YMCA – Summer Sparks Camp",
    town: "Maplewood",
    type: "STEM",
    description: "A brand-new 2026 YMCA enrichment camp for grades 1–6. Details to be finalized — an exciting addition to the Y's growing summer lineup.",
    ageMin: 6,
    ageMax: 12,
    dates: "Summer 2026 (dates TBA)",
    price: "Contact for rates",
    location: "Maplewood, NJ",
    contact: "info@metroymcas.org",
    phone: "(973) 758-9039",
    website: "https://maplewoodymcacamp.org/summer-sparks",
    tags: ["STEM", "enrichment", "YMCA", "new 2026"],
    featured: false
  },
  {
    id: 24,
    name: "South Mountain YMCA – Basketball Camp",
    town: "Maplewood",
    type: "Sports",
    description: "A specialty basketball camp for campers entering grades 2–6. Focuses on fundamentals, skill development, drills, and competitive play in a supportive environment.",
    ageMin: 7,
    ageMax: 12,
    dates: "Summer 2026 (dates TBA)",
    price: "Contact for rates",
    location: "South Mountain YMCA, 13 Jefferson Ave., Maplewood, NJ",
    contact: "info@metroymcas.org",
    phone: "(973) 762-4145",
    website: "https://maplewoodymcacamp.org/basketballcamp",
    tags: ["basketball", "sports", "YMCA", "skills"],
    featured: false
  },
  {
    id: 25,
    name: "South Mountain YMCA – Gymnastics Clinic",
    town: "Maplewood",
    type: "Sports",
    description: "A summer gymnastics clinic for campers entering grades 1–8. Directed by Lena Barnett. Covers beginner through intermediate skills.",
    ageMin: 6,
    ageMax: 14,
    dates: "Summer 2026 (dates TBA)",
    price: "Contact for rates",
    location: "South Mountain YMCA, 13 Jefferson Ave., Maplewood, NJ",
    contact: "info@metroymcas.org",
    phone: "(973) 762-4145",
    website: "https://maplewoodymcacamp.org/gymnastics",
    tags: ["gymnastics", "sports", "indoor", "YMCA"],
    featured: false
  },
  {
    id: 26,
    name: "South Mountain YMCA – Skate Camp",
    town: "Maplewood",
    type: "Sports",
    description: "A skateboarding day camp for grades 2–5. One of the only skate-specific camps in the SOMA area.",
    ageMin: 7,
    ageMax: 11,
    dates: "Summer 2026 (dates TBA)",
    price: "Contact for rates",
    location: "South Mountain YMCA / outdoor area, Maplewood, NJ",
    contact: "info@metroymcas.org",
    phone: "(973) 762-4145",
    website: "https://maplewoodymcacamp.org/skateboarding",
    tags: ["skateboarding", "sports", "outdoor", "YMCA"],
    featured: false
  },
  {
    id: 27,
    name: "South Mountain YMCA – Counselor in Training (CIT)",
    town: "Maplewood",
    type: "General",
    description: "A leadership development program for teens entering grades 9–10. CITs work alongside counselors and build mentorship and professional skills. Directed by Courtney Labossiere.",
    ageMin: 14,
    ageMax: 16,
    dates: "Summer 2026 (dates TBA)",
    price: "Contact for rates",
    location: "South Mountain YMCA, 13 Jefferson Ave., Maplewood, NJ",
    contact: "info@metroymcas.org",
    phone: "(973) 762-4145",
    website: "https://maplewoodymcacamp.org/counselor-in-training",
    tags: ["leadership", "teens", "CIT", "YMCA"],
    featured: false
  },
  {
    id: 28,
    name: "Maplewood Kids Camp",
    town: "Maplewood",
    type: "General",
    description: "Maplewood Township's official municipal day camp for kids entering Kindergarten through 5th grade. Pool trips, arts and crafts, and outdoor activities. Full-day, before-care, and after-care options available — call to register for extended care.",
    ageMin: 5,
    ageMax: 11,
    dates: "Summer 2026 (dates TBA)",
    price: "Contact for rates",
    location: "Maplewood, NJ",
    contact: "JMiranda@twp.maplewood.nj.us",
    phone: "(973) 762-8120",
    website: "https://www.maplewoodnj.gov/government/community-services/recreation/youth-programming/camp-programs",
    tags: ["day camp", "general", "swimming", "arts and crafts", "outdoor", "municipal"],
    featured: false
  },
  {
    id: 29,
    name: "Maplewood Summer Tennis Camp",
    town: "Maplewood",
    type: "Sports",
    description: "Municipal tennis camp for ages 6–14 at Memorial Park and Walter Park courts. Mon–Thu, 9am–12pm (Fri rain makeup). Covers stroke production, drills, singles and doubles tactics, and fitness.",
    ageMin: 6,
    ageMax: 14,
    dates: "Two sessions, summer 2026 (dates TBA)",
    price: "Contact for rates",
    location: "Memorial Park / Walter Park Tennis Courts, Maplewood, NJ",
    contact: "JMiranda@twp.maplewood.nj.us",
    phone: "(973) 762-8120",
    website: "https://www.maplewoodnj.gov/government/community-services/recreation/youth-programming/camp-programs",
    tags: ["tennis", "sports", "outdoor", "municipal"],
    featured: false
  },
  {
    id: 30,
    name: "Maplewood Club Tennis Camp",
    town: "Maplewood",
    type: "Sports",
    description: "One of the area's most established tennis camps, run by Director Tom Battaglia — an NCAA D1 head coach and USTA Lead Faculty Coach. Ages 5–16, all ability levels. Half-day and full-day options. Features the Maplewood Cup team competition. Sells out quickly — register early.",
    ageMin: 5,
    ageMax: 16,
    dates: "June 23 – August 21, 2026 (weekly, Mon–Thu; Fri rain makeup)",
    price: "$210–$260/week half-day (member/non-member); contact for full-day",
    location: "The Maplewood Club, Maplewood, NJ",
    contact: "Contact via website",
    phone: "Contact for info",
    website: "https://www.maplewoodclub.com/summer-camp",
    tags: ["tennis", "sports", "outdoor", "competitive", "all levels"],
    featured: false
  },
  {
    id: 31,
    name: "Maplewood Recreation – Multi-Sports Camp",
    town: "Maplewood",
    type: "Sports",
    description: "Weekly sports camps through Maplewood Recreation via USA Sport Group. Soccer, tennis, basketball, lacrosse, golf, t-ball, flag football, track & field, pickleball, field hockey, cricket, and multi-sport. Ages 2–18, all ability levels.",
    ageMin: 3,
    ageMax: 18,
    dates: "Weekly sessions throughout summer 2026",
    price: "Contact for rates",
    location: "Various parks, Maplewood, NJ",
    contact: "JMiranda@twp.maplewood.nj.us",
    phone: "(973) 762-8120",
    website: "https://usasportgroup.com/recreation/519-maplewood-recreation-maplewood-nj",
    tags: ["sports", "soccer", "tennis", "lacrosse", "basketball", "multi-sport", "outdoor"],
    featured: false
  },
  {
    id: 32,
    name: "MapleCraft Summer Art Camp",
    town: "Maplewood",
    type: "Arts",
    description: "A Maplewood Township art camp at the community art studio. Multiple rotating stations — kids choose their own projects around a weekly theme. Drawing, painting, sculpture, mixed media, and games. Supervised outdoor time each day.",
    ageMin: 5,
    ageMax: 12,
    dates: "Summer 2026 (dates TBA)",
    price: "Contact for rates",
    location: "Maplewood Community Arts Studio, Maplewood, NJ",
    contact: "JMiranda@twp.maplewood.nj.us",
    phone: "(973) 762-8120",
    website: "https://www.maplewoodnj.gov/government/community-services/recreation/youth-programming/camp-programs",
    tags: ["art", "crafts", "creative", "painting", "drawing", "municipal"],
    featured: false
  },
  {
    id: 33,
    name: "MapSo Summer Slam Basketball Camp",
    town: "Maplewood",
    type: "Sports",
    description: "A summer basketball camp for the Maplewood–South Orange community. Fundamentals, skill development, and competitive play. Part of Maplewood Community Services' summer lineup.",
    ageMin: 7,
    ageMax: 15,
    dates: "Summer 2026 (dates TBA)",
    price: "Contact for rates",
    location: "Maplewood, NJ",
    contact: "JMiranda@twp.maplewood.nj.us",
    phone: "(973) 762-8120",
    website: "https://www.maplewoodnj.gov/government/community-services/recreation/youth-programming/camp-programs",
    tags: ["basketball", "sports", "indoor", "skills"],
    featured: false
  },
  {
    id: 34,
    name: "Maplewood Mermaid Camp",
    town: "Maplewood",
    type: "Sports",
    description: "A swim-themed camp at the Maplewood Community Pool combining swim instruction, pool games, and mermaid-themed water play.",
    ageMin: 5,
    ageMax: 12,
    dates: "Summer 2026 (dates TBA)",
    price: "Contact for rates",
    location: "Maplewood Community Pool, Maplewood, NJ",
    contact: "JMiranda@twp.maplewood.nj.us",
    phone: "(973) 762-8120",
    website: "https://www.maplewoodnj.gov/government/community-services/recreation/youth-programming/camp-programs",
    tags: ["swimming", "pool", "outdoor", "water"],
    featured: false
  },
  {
    id: 35,
    name: "Maplewood Ultimate Frisbee Camp",
    town: "Maplewood",
    type: "Sports",
    description: "A specialty summer camp focused on Ultimate Frisbee. Athletic training, team strategy, and sportsmanship outdoors. Run by Maplewood Community Services.",
    ageMin: 8,
    ageMax: 15,
    dates: "Summer 2026 (dates TBA)",
    price: "Contact for rates",
    location: "Maplewood, NJ",
    contact: "JMiranda@twp.maplewood.nj.us",
    phone: "(973) 762-8120",
    website: "https://www.maplewoodnj.gov/government/community-services/recreation/youth-programming/camp-programs",
    tags: ["frisbee", "sports", "outdoor", "team"],
    featured: false
  },
  {
    id: 36,
    name: "Performers Theatre Workshop – Summer Broadway Camp",
    town: "Maplewood",
    type: "Arts",
    description: "A long-established Maplewood performing arts institution founded in 1983. Multiple summer tracks: Broadway Showcase & Training (ages 9–18), Broadway Conservatory (ages 9–18), and Young Performers (ages 4–8). Voice, acting, ballet/modern, jazz/hip-hop, tap, and musical theater. Junior campers perform locally; senior conservatory students perform at 'Don't Tell Mama' in NYC's Broadway district. Staff includes Broadway, TV, and film veterans.",
    ageMin: 4,
    ageMax: 18,
    dates: "Two 3-week sessions (contact for 2026 dates)",
    price: "Contact for rates; payment plans and early registration discounts available",
    location: "1 Pierson Road, Maplewood, NJ",
    contact: "ptwstars@gmail.com",
    phone: "(973) 327-2250",
    website: "https://ptwonline.com/classes-lessons/summer-programs/",
    tags: ["theater", "Broadway", "acting", "singing", "dance", "musical theater", "NYC showcase"],
    featured: true
  },
  {
    id: 37,
    name: "Lydia Johnson Dance School – Dance + Art Camp (Maplewood)",
    town: "Maplewood",
    type: "Arts",
    description: "The LJD Dance + Art Camp draws heavily from Maplewood families and has historically been held at the Burgdorff Performing Arts Center in Maplewood village. In 2026 the camp runs at St. Andrew's in South Orange, but this nonprofit school serves both towns equally. Taught by professional NYC company dancers. Scholarships available.",
    ageMin: 6,
    ageMax: 16,
    dates: "July 6–10 and July 13–17, 2026",
    price: "Contact for rates; scholarships available",
    location: "St. Andrew's Church, South Orange (see SO listing for full details)",
    contact: "lydiajohnsondance@gmail.com",
    phone: "Contact via website",
    website: "https://www.lydiajohnsondanceschool.com",
    tags: ["dance", "ballet", "modern", "art", "choreography", "nonprofit"],
    featured: false
  },
  {
    id: 38,
    name: "Maplewood School & Summer Program",
    town: "Maplewood",
    type: "General",
    description: "A long-running private full-day summer program featuring daily swim (Giant Water Slide!), age-appropriate sports with adapted equipment, field trips, and enrichment. Senior pool and Aqua Tot pool with American Red Cross-certified staff. Morning care, afternoon care, and bus service available. $1,000 deposit holds a spot.",
    ageMin: 3,
    ageMax: 14,
    dates: "Summer 2026 (contact for calendar; balance due April 1, 2026)",
    price: "Contact for 2026 rates",
    location: "Maplewood School, Maplewood, NJ",
    contact: "Contact via website",
    phone: "Contact for info",
    website: "https://www.maplewoodschool.com/summer-program/",
    tags: ["day camp", "swimming", "sports", "field trips", "general", "private"],
    featured: false
  },
  {
    id: 39,
    name: "Dingers NJ – Baseball & Softball Summer Camp",
    town: "Maplewood",
    type: "Sports",
    description: "Full-day baseball and softball camp at Dingers NJ, a state-of-the-art indoor training facility on Burnett Ave. Rain-or-shine: live games, HitTrax batting simulation, pool days at the Maplewood pool, whiffle ball tournaments, and Ice Cream Fridays. Rainy days: movies, bounce houses, indoor soccer, ping pong, and arcade. Aftercare available. Separate sessions for ages 6–11 and 12+.",
    ageMin: 7,
    ageMax: 13,
    dates: "Weekly sessions starting June 1, 2026 (registration open now)",
    price: "$200/week half-day clinic; contact for full-day camp rates",
    location: "Dingers NJ, 50–58 Burnett Ave, Maplewood, NJ",
    contact: "dingersnj@gmail.com",
    phone: "(973) 330-0767",
    website: "https://dingersnj.com",
    tags: ["baseball", "softball", "sports", "indoor", "batting", "HitTrax"],
    featured: false
  },
  {
    id: 40,
    name: "Kitchen Table – Kids Cooking Summer Camp",
    town: "Maplewood",
    type: "General",
    description: "A hands-on cooking camp for kids ages 8–12 at Kitchen Table, a beloved culinary studio on Springfield Ave. Led by professional chefs, campers cook and eat real food together each session. Weekly rotating themes. Camp runs July 6–August 16, 2026. Nut-free facility. Co-founded by a French Culinary Institute graduate who previously ran a children's cooking program on the Upper East Side.",
    ageMin: 8,
    ageMax: 12,
    dates: "July 6 – August 16, 2026 (weekly sessions)",
    price: "Contact for rates",
    location: "Kitchen Table, 1851 Springfield Ave (FL 2), Maplewood, NJ",
    contact: "Contact via website",
    phone: "(917) 414-4970",
    website: "https://www.kitchentablemaplewood.com",
    tags: ["cooking", "culinary", "food", "hands-on", "creative", "indoor"],
    featured: false
  },
  {
    id: 41,
    name: "SOMA Softball Camp",
    town: "Maplewood",
    type: "Sports",
    description: "A youth softball camp run by Columbia High School varsity players in Maplewood. A grassroots community program connecting high school athletes with younger players. Check website for 2026 dates and registration.",
    ageMin: 6,
    ageMax: 14,
    dates: "Summer 2026 (contact for dates)",
    price: "Contact for rates",
    location: "Maplewood, NJ",
    contact: "Contact via Facebook page",
    phone: "Contact for info",
    website: "https://orgibbons77.wixsite.com/my-site",
    tags: ["softball", "sports", "outdoor", "community", "CHS"],
    featured: false
  },

  // ─────────────────────────────────────────────────────────────────────
  // VERIFY FOR 2026 — listed on helloSOMA 2025 camp guide; confirmed
  // to exist as programs but full 2026 details not yet published online.
  // Recommend calling/emailing each before promoting heavily.
  // ─────────────────────────────────────────────────────────────────────

  {
    id: 42,
    name: "Rocket Improv Summer Camp",
    town: "South Orange",
    type: "Arts",
    description: "An improv comedy and performance camp for rising 4th–10th graders in the SOMA area. Appeared on helloSOMA's 2025 camp guide. Verify 2026 dates and details directly with the organizer.",
    ageMin: 9,
    ageMax: 16,
    dates: "Summer 2026 (verify with provider)",
    price: "Contact for rates",
    location: "South Orange / Maplewood area (verify with provider)",
    contact: "Contact via website",
    phone: "Contact for info",
    website: "https://www.hellosoma.com/summer-camps",
    tags: ["improv", "comedy", "theater", "arts", "teens"],
    featured: false
  },
  {
    id: 43,
    name: "SewLeana Fiber Arts Summer Camp",
    town: "Maplewood",
    type: "Arts",
    description: "A fiber arts and sewing camp with two tracks: Hand Sewing (ages 5–7) and Machine Sewing (ages 8+, morning and afternoon sessions). A unique, hands-on craft offering in the SOMA area. Appeared on helloSOMA's 2025 camp guide — verify 2026 details directly.",
    ageMin: 5,
    ageMax: 14,
    dates: "Summer 2026 (verify with provider)",
    price: "Contact for rates",
    location: "Maplewood / South Orange area (verify with provider)",
    contact: "Contact via website",
    phone: "Contact for info",
    website: "https://www.hellosoma.com/summer-camps",
    tags: ["sewing", "fiber arts", "crafts", "creative", "hands-on"],
    featured: false
  },
  {
    id: 44,
    name: "Motion Arts Dance Studios Summer Camp",
    town: "Maplewood",
    type: "Arts",
    description: "A summer dance camp with multiple age-group tracks (ages 6–8, 9–11, 12+, 13+). Appeared on helloSOMA's 2025 camp guide. Verify 2026 schedule, location, and pricing directly with Motion Arts.",
    ageMin: 6,
    ageMax: 17,
    dates: "Summer 2026 (verify with provider)",
    price: "Contact for rates",
    location: "Maplewood / South Orange area (verify with provider)",
    contact: "Contact via website",
    phone: "Contact for info",
    website: "https://www.hellosoma.com/summer-camps",
    tags: ["dance", "arts", "performing arts", "multiple ages"],
    featured: false
  },
  {
    id: 45,
    name: "NJ Fencing Alliance Summer Program",
    town: "Maplewood",
    type: "Sports",
    description: "The NJ Fencing Alliance, based in Maplewood, offers year-round youth fencing with Olympians on staff and is a statewide draw. Appeared on helloSOMA's camp guide — contact directly to confirm 2026 summer camp format and registration.",
    ageMin: 8,
    ageMax: 18,
    dates: "Summer 2026 (verify with provider)",
    price: "Contact for rates",
    location: "NJ Fencing Alliance, Maplewood, NJ",
    contact: "Contact via website",
    phone: "Contact for info",
    website: "https://www.hellosoma.com/summer-camps",
    tags: ["fencing", "sports", "Olympic", "indoor", "skills"],
    featured: false
  },

// ============================================================
// LIVINGSTON LISTINGS — add these to your campData array
// ============================================================

  {
    id: "liv-001",
    name: "Livingston Recreation Kids' Camp",
    town: "Livingston",
    type: ["general", "municipal"],
    description: "The flagship Livingston Rec summer camp for grades 1–6. Two pool days per week at Haines Pool, arts and crafts, STEM classes, sports, gaga, water play, and optional field trips. Full-day and half-day options available.",
    ageMin: 6,
    ageMax: 12,
    dates: "June 24 – August 7, 2026 (no camp July 3)",
    price: "Contact for 2026 rates",
    location: "Mount Pleasant Middle School, Livingston, NJ",
    contact: "recreation@livingstonnj.org",
    phone: "973-535-7925",
    website: "https://www.livingstonnj.org/1121/Kids-Camp-Grades-1---6-Fall-2026",
    tags: ["day camp", "sports", "arts", "general", "municipal"],
    featured: false
  },

  {
    id: "liv-002",
    name: "Livingston Recreation Kiddie Camp (Preschool)",
    town: "Livingston",
    type: ["general", "municipal"],
    description: "Introductory camp experience for Pre-K and Kindergarten children. Daily crafts, story time, outdoor playground, songs, and games. Small groups, big smiles. Half-day and full-day options.",
    ageMin: 3,
    ageMax: 6,
    dates: "June 24 – August 7, 2026",
    price: "$200/week",
    location: "Monmouth Court Community Center, 26 Monmouth Court, Livingston, NJ",
    contact: "recreation@livingstonnj.org",
    phone: "973-535-7925",
    website: "https://www.livingstonnj.org/792/Kiddie-Camp---Preschool",
    tags: ["day camp", "preschool", "general", "municipal"],
    featured: false
  },

  {
    id: "liv-003",
    name: "Livingston Recreation Tots Camp",
    town: "Livingston",
    type: ["general", "municipal"],
    description: "Designed for 2–3 year olds (DOB 10/1/22–9/30/23), this half-day camp is a wonderful first socialization experience. Daily crafts, songs, storytime, and parachute play in the preschool wing.",
    ageMin: 2,
    ageMax: 3,
    dates: "June 24 – August 7, 2026",
    price: "Contact for 2026 rates",
    location: "Livingston Senior/Community Center, 204 Hillside Avenue, Livingston, NJ",
    contact: "recreation@livingstonnj.org",
    phone: "973-535-7925",
    website: "https://www.livingstonnj.org/794/Tots-Camp-2-to-3-years-old",
    tags: ["toddler", "preschool", "day camp", "municipal"],
    featured: false
  },

  {
    id: "liv-004",
    name: "Livingston Recreation Teen Travel Camp",
    town: "Livingston",
    type: ["travel", "municipal"],
    description: "Field trips every day Monday–Thursday, plus a pool day on Fridays at Haines Pool Complex. Six weeks of adventure for incoming 7th and 8th graders. Resident and non-resident pricing available.",
    ageMin: 12,
    ageMax: 14,
    dates: "June 29 – August 7, 2026 (six weeks)",
    price: "$700/week resident; $800/week non-resident",
    location: "Drop-off/pick-up: Livingston Senior/Community Center, 204 Hillside Avenue",
    contact: "recreation@livingstonnj.org",
    phone: "973-535-7925",
    website: "https://www.livingstonnj.org/783/Teen-Travel-Grades-7-8-Fall-2026",
    tags: ["teen", "travel", "day camp", "municipal"],
    featured: false
  },

  {
    id: "liv-005",
    name: "Lancer Sports Camps",
    town: "Livingston",
    type: ["sports", "municipal"],
    description: "Sport-specific week-long camps run by Livingston High School's own coaching staff. Options include basketball, soccer, tennis, flag rugby, baseball, football, volleyball, field hockey, speed & agility track, and martial arts. Afternoon pool time at Haines Pool included with all full-day camps.",
    ageMin: 9,
    ageMax: 14,
    dates: "Various weeks June 29 – August 7, 2026",
    price: "$300/week resident; $400/week non-resident",
    location: "Livingston High School & Haines Pool, Livingston, NJ",
    contact: "recreation@livingstonnj.org",
    phone: "973-535-7925",
    website: "https://www.livingstonnj.org/709/Lancer-Sport-Camps-SUMMER",
    tags: ["sports", "basketball", "soccer", "tennis", "municipal"],
    featured: false
  },

  {
    id: "liv-006",
    name: "Livingston Recreation Theater & Dance Camp",
    town: "Livingston",
    type: ["arts", "performing arts", "municipal"],
    description: "NYC-caliber dance and theater training brought to Livingston. Ballet, tap, jazz, Broadway musical theater, vocal technique, acting, monologue, and improv. All ages K–10th grade, grouped by age and ability. Culminates in a Cabaret Show for families on August 21.",
    ageMin: 5,
    ageMax: 16,
    dates: "August 10 – 21, 2026",
    price: "$650 resident; $750 non-resident",
    location: "Livingston Senior/Community Center, 204 Hillside Avenue (lower level)",
    contact: "recreation@livingstonnj.org",
    phone: "973-535-7925",
    website: "https://www.livingstonnj.org/800/Theater-Dance-Camp",
    tags: ["performing arts", "dance", "theater", "arts", "municipal"],
    featured: false
  },

  {
    id: "liv-007",
    name: "Code Ninjas Summer Camp (Livingston)",
    town: "Livingston",
    type: ["STEM", "coding"],
    description: "Weekly coding camps for grades K–5 in partnership with Livingston Rec. Game-based curriculum that teaches sequencing, events, and loops through hands-on challenges including robotics (LEGO Spike), Minecraft modding, and AI filmmaking using YouTube's AI Playground.",
    ageMin: 5,
    ageMax: 11,
    dates: "Various weeks, Summer 2026",
    price: "Contact for 2026 rates",
    location: "Livingston Senior/Community Center, 204 Hillside Avenue",
    contact: "recreation@livingstonnj.org",
    phone: "973-535-7925",
    website: "https://www.livingstonnj.org/1158/Code-Ninjas-Weekly-Summer-Camp-2026",
    tags: ["STEM", "coding", "robotics", "technology", "municipal"],
    featured: false
  },

  {
    id: "liv-008",
    name: "Creatif Art & STEM Camp (Livingston)",
    town: "Livingston",
    type: ["arts", "STEM"],
    description: "Weekly themed art and STEM camps for ages 5–10 in Creatif's award-winning Livingston studio. Campers explore painting, ceramics, clay, and mixed media while building teamwork and critical thinking. Full-day and half-day options.",
    ageMin: 5,
    ageMax: 10,
    dates: "Various weekly sessions, Summer 2026",
    price: "Contact for 2026 rates",
    location: "Creatif Livingston, Livingston, NJ",
    contact: "Contact via website",
    phone: "Contact for info",
    website: "https://www.creatif.com/livingston-nj/camp/",
    tags: ["arts", "STEM", "creative", "private"],
    featured: false
  },

  {
    id: "liv-009",
    name: "VSA Future Educational Summer Camp",
    town: "Livingston",
    type: ["academic"],
    description: "Academic enrichment camp blending language arts, reading comprehension, public speaking, and vocabulary Mon–Thu with Mad Science and themed creative activities on Fridays. Small classes, individual attention, grades K–6. Full-day and half-day available.",
    ageMin: 5,
    ageMax: 12,
    dates: "July 20 – August 14, 2026 (weekly enrollment)",
    price: "Contact for 2026 rates",
    location: "VSA Future, Livingston, NJ",
    contact: "admin@vsafuture.com",
    phone: "Contact for info",
    website: "https://vsafuture.com/summer-camp-vsa/",
    tags: ["academic", "enrichment", "STEM", "reading", "private"],
    featured: false
  },

  {
    id: "liv-010",
    name: "Musical Theatre Conservatory Broadway Boot Camp",
    town: "Livingston",
    type: ["performing arts", "arts"],
    description: "Three-week intensive for aspiring performers ages 7–19, run by the Musical Theatre Conservatory at their West Orange/Livingston location. Vocal technique, scene study, TV acting, dance, audition coaching, and a live NJ showcase performance. All levels welcome.",
    ageMin: 7,
    ageMax: 19,
    dates: "July 7 – 25, 2026",
    price: "Contact for 2026 rates",
    location: "Musical Theatre Conservatory, West Orange/Livingston, NJ",
    contact: "Contact via website",
    phone: "973-868-6259",
    website: "https://www.musicaltheatreconservatory.com",
    tags: ["performing arts", "theater", "voice", "dance", "private"],
    featured: false
  },


// ============================================================
// MILLBURN LISTINGS — add these to your campData array
// ============================================================

  {
    id: "mil-001",
    name: "Millburn Recreation Mini-Day Camp",
    town: "Millburn",
    type: ["general", "municipal"],
    description: "Millburn Rec's half-day summer camp for young children. Daily activities, crafts, games, and themed adventures in a fun, structured environment.",
    ageMin: 4,
    ageMax: 8,
    dates: "Summer 2026 (contact for exact dates)",
    price: "Contact for 2026 rates",
    location: "Millburn Township Recreation, Millburn, NJ",
    contact: "recreationdept@millburntwp.org",
    phone: "973-564-7097",
    website: "https://twp.millburn.nj.us/404/Program-Registration-Forms",
    tags: ["day camp", "preschool", "general", "municipal"],
    featured: false
  },

  {
    id: "mil-002",
    name: "Millburn Recreation Junior Day Camp",
    town: "Millburn",
    type: ["general", "municipal"],
    description: "Full-day summer camp for elementary-age kids through Millburn Township Recreation. Sports, crafts, swimming, and weekly themed fun in a classic camp environment.",
    ageMin: 6,
    ageMax: 11,
    dates: "Summer 2026 (contact for exact dates)",
    price: "Contact for 2026 rates",
    location: "Millburn Township Recreation, Millburn, NJ",
    contact: "recreationdept@millburntwp.org",
    phone: "973-564-7097",
    website: "https://twp.millburn.nj.us/404/Program-Registration-Forms",
    tags: ["day camp", "general", "sports", "municipal"],
    featured: false
  },

  {
    id: "mil-003",
    name: "Millburn Recreation TGIS Camp (Ages 11–14)",
    town: "Millburn",
    type: ["general", "municipal"],
    description: "Summer camp designed for tweens and early teens ages 11–14. Activities, field trips, and social experiences geared specifically for older campers.",
    ageMin: 11,
    ageMax: 14,
    dates: "Summer 2026 (contact for exact dates)",
    price: "Contact for 2026 rates",
    location: "Millburn Township Recreation, Millburn, NJ",
    contact: "recreationdept@millburntwp.org",
    phone: "973-564-7097",
    website: "https://twp.millburn.nj.us/404/Program-Registration-Forms",
    tags: ["teen", "day camp", "general", "municipal"],
    featured: false
  },

  {
    id: "mil-004",
    name: "Millburn Recreation Summer Sports Camps (USA Sport Group)",
    town: "Millburn",
    type: ["sports", "municipal"],
    description: "Multi-sport and single-sport summer camps through Millburn Rec in partnership with USA Sport Group. Options include soccer, tennis, lacrosse, basketball, golf, flag football, and multi-sport. Age-appropriate and suitable for all ability levels, ages 2–18.",
    ageMin: 2,
    ageMax: 18,
    dates: "Various weekly sessions, Summer 2026",
    price: "Contact for 2026 rates",
    location: "Various Millburn Recreation sites, Millburn, NJ",
    contact: "recreationdept@millburntwp.org",
    phone: "973-564-7097",
    website: "https://usasportgroup.com/recreation/156-millburn-recreation-millburn-nj",
    tags: ["sports", "soccer", "tennis", "multi-sport", "municipal"],
    featured: false
  },

  {
    id: "mil-005",
    name: "Paper Mill Playhouse Summer Studio",
    town: "Millburn",
    type: ["performing arts", "arts"],
    description: "Four weeks of acting, dance, and musical theatre workshops at New Jersey's most acclaimed professional theater. Limited spots that sell out every summer. Part of Paper Mill's broader summer training offerings which include an audition-based Conservatory and Musical Theater Intensive for serious performers ages 10–18.",
    ageMin: 8,
    ageMax: 18,
    dates: "June 29 – August 21, 2026",
    price: "Contact for 2026 rates",
    location: "Paper Mill Playhouse, 22 Brookside Drive, Millburn, NJ 07041",
    contact: "summer@papermill.org",
    phone: "973-376-4343",
    website: "https://papermill.org/education/summer-training/camp/",
    tags: ["performing arts", "theater", "dance", "musical theater", "private"],
    featured: true
  },

  {
    id: "mil-006",
    name: "Performers Theatre Workshop (PTW) Summer Camp",
    town: "Millburn",
    type: ["performing arts", "arts"],
    description: "NJ's premier performing arts school, founded by Juilliard graduates, offers multiple summer programs at their state-of-the-art Millburn facility. PTW Junior Camp (ages 5–8) covers singing, acting, and dance over three-week sessions. The Summer Broadway Showcase & Conservatory (ages 9–18) trains performers in musical theater, voice, acting, and dance — culminating in a live NYC showcase at 54 Below attended by industry agents and managers.",
    ageMin: 5,
    ageMax: 18,
    dates: "Multiple sessions, June 30 – August 2026",
    price: "Contact for 2026 rates",
    location: "131 Millburn Ave, Millburn, NJ 07041",
    contact: "ptwstars@gmail.com",
    phone: "973-327-2250",
    website: "https://ptwonline.com/summer-programs/",
    tags: ["performing arts", "theater", "voice", "dance", "private"],
    featured: false
  },

  {
    id: "mil-007",
    name: "One River School Summer Art Camps (Millburn)",
    town: "Millburn",
    type: ["arts"],
    description: "90+ weekly half-day and full-day art camps run by practicing artists, designers, and animators. Covers drawing, painting, digital art, Procreate, animation, and contemporary techniques. Camps for kids and teens; bundle morning and afternoon for a full day. Friday parent showcases each week.",
    ageMin: 5,
    ageMax: 18,
    dates: "10 weeks of camps, Summer 2026 (various start dates)",
    price: "Contact for 2026 rates",
    location: "One River School, Millburn, NJ",
    contact: "Contact via website",
    phone: "Contact for info",
    website: "https://millburn.oneriverschool.com/camps/",
    tags: ["arts", "visual arts", "creative", "animation", "private"],
    featured: false
  },

  {
    id: "mil-008",
    name: "Lou Ruina Summer Golf Camp",
    town: "Millburn",
    type: ["sports", "municipal"],
    description: "Summer golf camp for youth at the Millburn Par 3 Golf Course, run through Millburn Township Recreation. Hands-on instruction on the 9-hole, par-3 tree-lined course in Short Hills.",
    ageMin: 7,
    ageMax: 16,
    dates: "Summer 2026 (contact for exact dates)",
    price: "Contact for 2026 rates",
    location: "Millburn Par 3 Golf Course, 335 White Oak Ridge Road, Short Hills, NJ",
    contact: "recreationdept@millburntwp.org",
    phone: "973-564-7097",
    website: "https://twp.millburn.nj.us/404/Program-Registration-Forms",
    tags: ["sports", "golf", "municipal"],
    featured: false
  },

  {
    id: "mil-009",
    name: "Genius Gems STEM Mini-Camps (Millburn)",
    town: "Millburn",
    type: ["STEM"],
    description: "Single-day drop-in STEM mini-camps for kindergartners and up at the Millburn location. Each day has a different theme — Mad Science Lab, Tech & Innovation, Code & Create — with hands-on projects and magnetic tile building. Flexible, à-la-carte scheduling.",
    ageMin: 5,
    ageMax: 12,
    dates: "Various days, Summer 2026",
    price: "$115/day",
    location: "Genius Gems, Millburn, NJ",
    contact: "Contact via website",
    phone: "Contact for info",
    website: "https://geniusgems.com/products/mini-camps-nj",
    tags: ["STEM", "science", "coding", "private"],
    featured: false
  },

  {
    id: "mil-010",
    name: "International Ivy Enrichment Summer Camp (Short Hills)",
    town: "Millburn",
    type: ["academic"],
    description: "Small-group (max 10 students) academic enrichment summer camp in Short Hills. Half-day and full-day options with morning and afternoon sessions. Early registration discounts available through spring.",
    ageMin: 5,
    ageMax: 14,
    dates: "Summer 2026 (contact for exact schedule)",
    price: "$480/week half-day; $960/week full-day",
    location: "Short Hills, NJ (Millburn Township)",
    contact: "Contact via website",
    phone: "Contact for info",
    website: "https://iisummer.com/short-hills/",
    tags: ["academic", "enrichment", "small group", "private"],
    featured: false
  },
  
// ============================================================
// ADDITIONAL LIVINGSTON LISTINGS — paste into campData array
// ============================================================

  {
    id: "liv-011",
    name: "West Essex YMCA Summer Day Camps",
    town: "Livingston",
    type: ["general", "sports"],
    description: "The only ACA-accredited camps in Livingston, with four distinct programs: Summer Sprouts (ages 3–5, pre-K only), Pioneer Trails (grades K–8, traditional day camp), Super Summer (grades K–6), and Teen Adventure Day Camp (grades 7–9). Financial assistance available through the Y for All Fund. Financial assistance available for families who qualify.",
    ageMin: 3,
    ageMax: 15,
    dates: "Summer 2026 (contact for exact dates and rates)",
    price: "From $350/week; contact for full rate schedule",
    location: "West Essex YMCA, 321 S. Livingston Ave, Livingston, NJ 07039",
    contact: "Contact via website",
    phone: "973-992-7500",
    website: "https://livingstonymcacamp.org/summer-camp",
    tags: ["day camp", "general", "sports", "swimming", "ACA-accredited"],
    featured: false
  },

  {
    id: "liv-012",
    name: "Livingston Recreation Last Blast Camp",
    town: "Livingston",
    type: ["general", "municipal"],
    description: "End-of-summer day camp held at Haines Pool for grades 1–6. Swimming, basketball, arts & crafts, games, and playground. Register per day or per week — flexible scheduling for late summer.",
    ageMin: 6,
    ageMax: 12,
    dates: "Late summer 2026 (contact for exact dates)",
    price: "Contact for 2026 rates",
    location: "Mervyn V.T. Haines Community Pool, 10 Wahler Road, Livingston, NJ",
    contact: "recreation@livingstonnj.org",
    phone: "973-535-7925",
    website: "https://www.livingstonnj.org/994/Last-Blast-Camp",
    tags: ["day camp", "swimming", "general", "municipal"],
    featured: false
  },

  {
    id: "liv-013",
    name: "Jump! Immersion Spanish & Mandarin Summer Camp",
    town: "Livingston",
    type: ["academic", "language"],
    description: "Language immersion summer camp for ages 3–11 offering Spanish or Mandarin Chinese. Authentic cultural games, outdoor activities, arts & crafts, and friendships in a fully immersive environment. Two-, three-, or five-day weekly options with before/after care available.",
    ageMin: 3,
    ageMax: 11,
    dates: "Summer 2026 (contact for exact dates)",
    price: "Contact for 2026 rates",
    location: "Jump Immersion School, 264 W. Northfield Rd, Livingston, NJ",
    contact: "Contact via website",
    phone: "732-371-2221",
    website: "https://jumpimmersion.com/registration-summer-camp",
    tags: ["language", "immersion", "Spanish", "Mandarin", "academic", "private"],
    featured: false
  },

  {
    id: "liv-014",
    name: "Snapology STEM/STEAM Summer Camps (Livingston)",
    town: "Livingston",
    type: ["STEM"],
    description: "Weekly themed STEM/STEAM camps using LEGO bricks, coding, robotics, and science for ages 5–12. Camps run year-round with school-break options too. A hands-on learning environment focused on creativity, critical thinking, and collaboration.",
    ageMin: 5,
    ageMax: 12,
    dates: "Various weekly sessions, Summer 2026",
    price: "Contact for 2026 rates",
    location: "Snapology, Livingston, NJ",
    contact: "Contact via website",
    phone: "Contact for info",
    website: "https://www.snapology.com/new-jersey-livingston/camps/",
    tags: ["STEM", "STEAM", "robotics", "coding", "LEGO", "private"],
    featured: false
  },

  {
    id: "liv-015",
    name: "Ady Art Center Dance & Arts Summer Camp",
    town: "Livingston",
    type: ["arts", "dance"],
    description: "Summer camp from a Livingston dance studio and art center offering classes in dance, music, visual arts, and performance. Open to children of various ages in a creative, nurturing studio environment.",
    ageMin: 4,
    ageMax: 14,
    dates: "Summer 2026 (contact for exact dates)",
    price: "Contact for 2026 rates",
    location: "Ady Art Center, Livingston, NJ",
    contact: "Contact via website",
    phone: "Contact for info",
    website: "http://www.adyartcenter.com/camp.html",
    tags: ["dance", "arts", "music", "private"],
    featured: false
  },

  {
    id: "liv-016",
    name: "Livingston Recreation Specialty Camps",
    town: "Livingston",
    type: ["general", "municipal"],
    description: "A rotating lineup of specialty week-long camps in August run by Livingston Rec, distinct from the standard Kids' Camp. Specific themes for 2026 will be posted on the town website — check back for updates.",
    ageMin: 6,
    ageMax: 12,
    dates: "August 2026 (exact dates TBA)",
    price: "Contact for 2026 rates",
    location: "Livingston Recreation, Livingston, NJ",
    contact: "recreation@livingstonnj.org",
    phone: "973-535-7925",
    website: "https://www.livingstonnj.org/1298/Specialty-Camps---August-2026",
    tags: ["specialty", "general", "municipal"],
    featured: false
  },


// ============================================================
// ADDITIONAL MILLBURN LISTINGS — paste into campData array
// ============================================================

  {
    id: "mil-011",
    name: "Genius Gems STEM Summer Camp (Millburn)",
    town: "Millburn",
    type: ["STEM"],
    description: "Wildly popular weekly STEM camp at 215 Millburn Ave for grades K–6 — almost all weeks sold out last summer, so early registration is critical. Weekly themes include Slime Lab, Kitchen Chemistry, Coding & Robots, LEGO Engineering, Mad Science, and Game Design Lab. Half-day ($349/week) at the Millburn studio; full-day ($575/week) at nearby Congregation B'nai Israel. Aftercare available.",
    ageMin: 5,
    ageMax: 12,
    dates: "10 weekly sessions, starting late June 2026",
    price: "$349/week half-day; $575/week full-day",
    location: "215 Millburn Ave, Millburn, NJ 07041 (half-day); 160 Millburn Ave at CBI (full-day)",
    contact: "information@geniusgems.com",
    phone: "973-376-2623",
    website: "https://geniusgems.com/pages/summer-2026-preview",
    tags: ["STEM", "coding", "science", "robotics", "engineering", "private"],
    featured: false
  },

  {
    id: "mil-012",
    name: "Millburn Recreation Playground Camp",
    town: "Millburn",
    type: ["general", "municipal"],
    description: "A classic outdoor Millburn township playground camp for kids, combining unstructured play with supervised activities in neighborhood parks.",
    ageMin: 5,
    ageMax: 11,
    dates: "Summer 2026 (contact for exact dates)",
    price: "Contact for 2026 rates",
    location: "Millburn Township Recreation, Millburn, NJ",
    contact: "recreationdept@millburntwp.org",
    phone: "973-564-7097",
    website: "https://twp.millburn.nj.us/404/Program-Registration-Forms",
    tags: ["day camp", "outdoor", "general", "municipal"],
    featured: false
  },

  {
    id: "mil-013",
    name: "Coach Nucci Summer Baseball Camp (Millburn)",
    town: "Millburn",
    type: ["sports", "municipal"],
    description: "Baseball-focused summer camp run through Millburn Recreation, offering instruction in hitting, fielding, pitching, and game strategy for youth players.",
    ageMin: 7,
    ageMax: 14,
    dates: "Summer 2026 (contact for exact dates)",
    price: "Contact for 2026 rates",
    location: "Millburn Township Recreation, Millburn, NJ",
    contact: "recreationdept@millburntwp.org",
    phone: "973-564-7097",
    website: "https://twp.millburn.nj.us/404/Program-Registration-Forms",
    tags: ["sports", "baseball", "municipal"],
    featured: false
  },

];
